// <auto-generated />
using System;
using Hongdal.Infrastructure.Persistence.AgriculturalFisheries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hongdal.Infrastructure.Persistence.AgriculturalFisheries.Migrations
{
    [DbContext(typeof(AgriculturalFisheriesDbContext))]
    partial class AgriculturalFisheriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.HsUsdaCommodityMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HsCode6")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("HsDescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MappingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MatchQualityCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ProductNameKo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ReviewOwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("ReviewStatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsdaClassDesc")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UsdaCommodityDesc")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("UsdaProductionPracticeDesc")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UsdaUtilPracticeDesc")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("MappingKey")
                        .IsUnique();

                    b.HasIndex("HsCode6", "IsActive");

                    b.HasIndex("ReviewStatusCode", "IsActive");

                    b.HasIndex("UsdaCommodityDesc", "IsActive");

                    b.ToTable("agri_hs_usda_commodity_mappings", (string)null);
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.KamisPriceCollectionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ExistingCount")
                        .HasColumnType("int");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LatestSurveyDate")
                        .HasColumnType("date");

                    b.Property<string>("QuerySummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<string>("RunKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedDate");

                    b.HasIndex("RunKey")
                        .IsUnique();

                    b.HasIndex("StatusCode", "StartedAtUtc");

                    b.ToTable("agri_kamis_price_collection_runs", (string)null);
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.KamisPriceObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("FirstCollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FirstCollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("FrequencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Daily");

                    b.Property<bool>("IsPriceMissing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KindCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KindName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalYearLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("NormalYearPriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("OneMonthAgoLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("OneMonthAgoPriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("OneWeekAgoLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("OneWeekAgoPriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("OneYearAgoLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("OneYearAgoPriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("PreviousDayLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("PreviousDayPriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<decimal?>("PriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("PriceRaw")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ProductClassCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("ProductClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateOnly>("SurveyDate")
                        .HasColumnType("date");

                    b.Property<string>("TwoWeeksAgoLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("TwoWeeksAgoPriceKrw")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FirstCollectionRunId");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("RecordKey")
                        .IsUnique();

                    b.HasIndex("ItemName", "SurveyDate");

                    b.HasIndex("SurveyDate", "FrequencyCode", "ProductClassCode", "CategoryCode", "ItemCode");

                    b.ToTable("agri_kamis_price_observations", (string)null);
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.UsdaNassPriceCollectionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ExistingCount")
                        .HasColumnType("int");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LatestSourceLoadTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QuerySummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RunKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("YearFrom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunKey")
                        .IsUnique();

                    b.HasIndex("StatusCode", "StartedAtUtc");

                    b.ToTable("agri_usda_nass_collection_runs", (string)null);
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.UsdaNassPriceObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AggregationLevelDesc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("BeginCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ClassDesc")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("CommodityDesc")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("CvPercentRaw")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DomainCategoryDesc")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("DomainDesc")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EndCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("FirstCollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FirstCollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("FrequencyDesc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("GroupDesc")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(24, 6)
                        .HasColumnType("decimal(24,6)");

                    b.Property<string>("ProductionPracticeDesc")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ReferencePeriodDesc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SectorDesc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SourceDesc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("SourceLoadTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("StatisticCategoryDesc")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("UnitDesc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("UtilPracticeDesc")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("ValueRaw")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirstCollectionRunId");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("RecordKey")
                        .IsUnique();

                    b.HasIndex("SourceLoadTimeUtc");

                    b.HasIndex("CommodityDesc", "Year", "FrequencyDesc", "ReferencePeriodDesc");

                    b.ToTable("agri_usda_nass_price_observations", (string)null);
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.KamisPriceObservation", b =>
                {
                    b.HasOne("Hongdal.Domain.AgriculturalFisheries.KamisPriceCollectionRun", "FirstCollectionRun")
                        .WithMany("NewObservations")
                        .HasForeignKey("FirstCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstCollectionRun");
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.UsdaNassPriceObservation", b =>
                {
                    b.HasOne("Hongdal.Domain.AgriculturalFisheries.UsdaNassPriceCollectionRun", "FirstCollectionRun")
                        .WithMany("NewObservations")
                        .HasForeignKey("FirstCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstCollectionRun");
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.KamisPriceCollectionRun", b =>
                {
                    b.Navigation("NewObservations");
                });

            modelBuilder.Entity("Hongdal.Domain.AgriculturalFisheries.UsdaNassPriceCollectionRun", b =>
                {
                    b.Navigation("NewObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
