<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>HongdalApp</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCssItems>false</EnableDefaultCssItems>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\HongdalApp\Components\**\*.razor" LinkBase="Components" />
    <Content Include="..\..\..\HongdalApp\wwwroot\**\*" LinkBase="wwwroot" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="..\..\..\HongdalApp\Models\**\*.cs" LinkBase="Models" />
    <Compile Include="..\..\..\HongdalApp\Options\**\*.cs" LinkBase="Options" />
    <Compile Include="..\..\..\HongdalApp\Services\**\*.cs" LinkBase="Services" />
    <Compile Include="..\..\..\HongdalApp\ViewModels\**\*.cs" LinkBase="ViewModels" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Hongdal.Contracts\Hongdal.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Hongdal.Client.Infrastructure\Hongdal.Client.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Hongdal.Ui.Common\Hongdal.Ui.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>
</Project>
