using Hongdal.Contracts.Common.AgriculturalFisheries;

namespace Hongdal.Services.AgriculturalFisheries.Information;

public static class UnitedStatesAgriculturalFisheriesOperatorSourceCatalog
{
    public static readonly DateOnly SnapshotReviewedOn = new(2026, 7, 18);

    public static IReadOnlyList<미국농어업경영체정보원천항목> Sources { get; } =
        Array.AsReadOnly(new[]
        {
            Source(
                "fda-interstate-certified-shellfish-shippers",
                "U.S. Food and Drug Administration (FDA)",
                "Interstate Certified Shellfish Shippers List (ICSSL)",
                [미국농어업경영체정보분야Codes.Aquaculture,
                    미국농어업경영체정보분야Codes.SeafoodProcessingAndShipping],
                미국농어업경영체정보기록유형Codes.CertifiedShipperDirectory,
                미국농어업경영체정보공개범위Codes.PublicBusinessDirectory,
                "미국 주·준주 및 협정 상대국",
                [미국농어업경영체정보접근방식Codes.DynamicSearch,
                    미국농어업경영체정보접근방식Codes.PdfDocument],
                미국농어업경영체정보통합상태Codes.OfficialLookupOnly,
                "https://www.fda.gov/food/federal-state-local-tribal-and-territorial-cooperative-human-food-programs/interstate-certified-shellfish-shippers-list",
                "https://hfpappexternal.fda.gov/scripts/shellfish/sh/shellfish.cfm",
                "동적 목록 수시 갱신, 인쇄용 목록 월별",
                canDiscoverBusinesses: true,
                canConfirmProgramStatus: true,
                containsPotentialPersonalData: true,
                ["업체명", "도시·주", "인증번호", "인증 활동 기호", "인증 만료일"],
                ["패류 공급·가공 후보 발견", "계약 전 최신 인증 상태의 공식 재확인"],
                ["목록 등재만으로 품목별 공급능력·계약권한 확정", "공개 연락처를 이용한 자동 초대·대량 발송"],
                ["패류 위생 프로그램의 인증 명부이며 미국 전체 수산업체 명부가 아닙니다."],
                "FDA Interstate Certified Shellfish Shippers List"),
            Source(
                "noaa-commercial-landings",
                "NOAA Fisheries",
                "Commercial Fisheries Landings Summaries",
                [미국농어업경영체정보분야Codes.WildCaptureFisheries],
                미국농어업경영체정보기록유형Codes.AggregateStatistics,
                미국농어업경영체정보공개범위Codes.PublicAggregateOnly,
                "미국 전국·주별 집계",
                [미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.MetadataCataloged,
                "https://www.fisheries.noaa.gov/commercial-landing-data-caveats",
                null,
                "자료 계열별 상이",
                canDiscoverBusinesses: false,
                canConfirmProgramStatus: false,
                containsPotentialPersonalData: false,
                ["주·어종별 양륙량", "양륙금액", "비공개 자료를 보호한 집계값"],
                ["수산시장 규모와 지역 맥락 분석"],
                ["개별 어업인·선박·업체 역추정", "집계자료를 업체 명부로 변환"],
                ["연방법상 기여자를 식별할 수 있는 양륙 자료는 공개되지 않습니다."],
                "NOAA Commercial Landing Data Caveats"),
            Source(
                "noaa-greater-atlantic-permits",
                "NOAA Fisheries Greater Atlantic Regional Fisheries Office",
                "Greater Atlantic Commercial Permit Data",
                [미국농어업경영체정보분야Codes.WildCaptureFisheries,
                    미국농어업경영체정보분야Codes.SeafoodProcessingAndShipping],
                미국농어업경영체정보기록유형Codes.PermitSummaryDirectory,
                미국농어업경영체정보공개범위Codes.PublicRegionalPermitSummary,
                "Greater Atlantic Region",
                [미국농어업경영체정보접근방식Codes.CsvDownload,
                    미국농어업경영체정보접근방식Codes.DynamicSearch],
                미국농어업경영체정보통합상태Codes.BulkIntegrationCandidate,
                "https://www.fisheries.noaa.gov/data-tools/public-permit-lookup",
                "https://apps-garfo.fisheries.noaa.gov/permits/",
                "허가 연도별·수시 갱신",
                canDiscoverBusinesses: true,
                canConfirmProgramStatus: true,
                containsPotentialPersonalData: true,
                ["선박·딜러·운영자 허가 요약", "허가번호", "허가 어업 종류"],
                ["사용자가 제시한 사업자·허가번호의 지역별 공식 대조", "동의 기반 참여 신청의 보조 증거"],
                ["소유자 주소·개인 연락처의 선제 수집", "미국 전국 허가로 일반화", "갱신 가능성 또는 거래 권한 보증"],
                ["Greater Atlantic 지역 자료이며 NOAA도 조회 결과가 갱신 가능성이나 최종 적격성을 보증하지 않는다고 명시합니다."],
                "NOAA Greater Atlantic Public Permit Lookup"),
            Source(
                "noaa-usdc-approved-establishments",
                "NOAA Fisheries Seafood Inspection Program",
                "U.S. Department of Commerce Approved Establishments",
                [미국농어업경영체정보분야Codes.SeafoodProcessingAndShipping],
                미국농어업경영체정보기록유형Codes.InspectedEstablishmentDirectory,
                미국농어업경영체정보공개범위Codes.PublicBusinessDirectory,
                "미국 및 승인된 국제 시설",
                [미국농어업경영체정보접근방식Codes.PdfDocument,
                    미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.OfficialLookupOnly,
                "https://www.fisheries.noaa.gov/resource/document/us-department-commerce-approved-establishments",
                null,
                "공식 문서 수시 갱신",
                canDiscoverBusinesses: true,
                canConfirmProgramStatus: true,
                containsPotentialPersonalData: true,
                ["시설·선박명", "시설번호", "위치", "승인된 제품·서비스 범주"],
                ["수산물 검사 프로그램 참여 시설 후보 확인", "계약 전 최신 문서 재확인"],
                ["미등재 시설을 부적격으로 단정", "NOAA 검사 참여를 모든 법적 허가의 대체로 사용"],
                ["유상·자발적 Seafood Inspection Program 참여 명부이며 미등재 시설의 위생 실패를 뜻하지 않습니다."],
                "NOAA U.S. Department of Commerce Approved Establishments"),
            Source(
                "usda-fsa-producer-program-records",
                "USDA Farm Service Agency (FSA)",
                "USDA Program Participant and Farm Records",
                [미국농어업경영체정보분야Codes.Agriculture,
                    미국농어업경영체정보분야Codes.Aquaculture],
                미국농어업경영체정보기록유형Codes.ConfidentialAdministrativeRecords,
                미국농어업경영체정보공개범위Codes.RestrictedIndividualRecords,
                "미국 전국",
                [미국농어업경영체정보접근방식Codes.Restricted],
                미국농어업경영체정보통합상태Codes.DoNotIngest,
                "https://www.fsa.usda.gov/Internet/FSA_Notice/app_70.pdf",
                null,
                "공개 데이터 원천 아님",
                canDiscoverBusinesses: false,
                canConfirmProgramStatus: false,
                containsPotentialPersonalData: true,
                [],
                ["공개 제한 경계와 예외 여부 확인"],
                ["농업 생산자·토지 소유자의 프로그램 제출정보, 농업 운영·보전 관행, 토지 지리정보 수집", "비공개 자료로 업체 명부 생성"],
                ["7 U.S.C. 8791에 따라 USDA 프로그램 참여 과정에서 제출된 개별 운영정보와 지리정보는 제한된 예외 외에는 공개가 금지됩니다."],
                "USDA FSA Section 1619 and Names and Addresses Under FOIA"),
            Source(
                "usda-fsis-inspection-directory",
                "USDA Food Safety and Inspection Service (FSIS)",
                "Meat, Poultry and Egg Product Inspection Directory",
                [미국농어업경영체정보분야Codes.MeatPoultryEggProcessing],
                미국농어업경영체정보기록유형Codes.InspectedEstablishmentDirectory,
                미국농어업경영체정보공개범위Codes.PublicBusinessDirectory,
                "미국 전국·준주",
                [미국농어업경영체정보접근방식Codes.CsvDownload,
                    미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.BulkIntegrationCandidate,
                "https://www.fsis.usda.gov/inspection/establishments/meat-poultry-and-egg-product-inspection-directory",
                null,
                "주별",
                canDiscoverBusinesses: true,
                canConfirmProgramStatus: true,
                containsPotentialPersonalData: true,
                ["시설명·시설번호", "물리적 위치", "시설 규모 범주", "도축 종·가공 활동 범주"],
                ["규제 대상 가공시설 후보 발견", "시설번호·활동 범주의 공식 대조"],
                ["특정 상품의 생산·수출 적격성 자동 판정", "시설 담당자 동의 없는 자동 참여 등록"],
                ["시설 단위 규제 명부이며 농장·목장 운영자 전체 명부가 아닙니다."],
                "USDA FSIS Meat, Poultry and Egg Product Inspection Directory"),
            Source(
                "usda-local-food-directories",
                "USDA Agricultural Marketing Service (AMS)",
                "USDA Local Food Directories",
                [미국농어업경영체정보분야Codes.Agriculture,
                    미국농어업경영체정보분야Codes.LocalFoodDistribution],
                미국농어업경영체정보기록유형Codes.VoluntaryBusinessDirectory,
                미국농어업경영체정보공개범위Codes.PublicBusinessDirectory,
                "미국 전국",
                [미국농어업경영체정보접근방식Codes.Api,
                    미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.BulkIntegrationCandidate,
                "https://www.ams.usda.gov/services/local-regional/food-directories-listings",
                "https://www.usdalocalfoodportal.com/fe/datasharing/",
                "사업자 자율 갱신",
                canDiscoverBusinesses: true,
                canConfirmProgramStatus: false,
                containsPotentialPersonalData: true,
                ["Farmers Market·CSA·Food Hub·On-Farm Market", "위치", "운영기간", "취급품목", "결제수단"],
                ["근거리 생산자·CSA·Food Hub 후보 발견", "우편번호 기반 공동구매 공급망 탐색"],
                ["목록의 완전성·최신성 보증", "자발적 등재를 정부 인증으로 표시", "자동 초대·대량 연락"],
                ["사업자 자발적 등재 자료이므로 미국 농업경영체 전체를 포괄하지 않습니다."],
                "USDA AMS Local Food Directory Listings"),
            Source(
                "usda-nass-census-agriculture",
                "USDA National Agricultural Statistics Service (NASS)",
                "Census of Agriculture",
                [미국농어업경영체정보분야Codes.Agriculture],
                미국농어업경영체정보기록유형Codes.AggregateStatistics,
                미국농어업경영체정보공개범위Codes.PublicAggregateOnly,
                "미국 전국·주·카운티 집계",
                [미국농어업경영체정보접근방식Codes.Api,
                    미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.IntegratedAggregateApi,
                "https://www.nass.usda.gov/AgCensus/",
                "https://quickstats.nass.usda.gov/api",
                "5년 주기 조사, Quick Stats 자료별 갱신",
                canDiscoverBusinesses: false,
                canConfirmProgramStatus: false,
                containsPotentialPersonalData: false,
                ["지역별 농장 수", "재배·사육·판매 집계", "운영자 특성 집계"],
                ["지역 수요·공급 규모 분석", "공동구매 후보 지역의 집계 맥락 제공"],
                ["개별 농장·운영자 식별", "소수 집계값을 다른 자료와 결합한 역추정"],
                ["NASS는 개별 또는 농장별 자료를 공개하지 않고 집계만 공개합니다."],
                "USDA NASS Census of Agriculture"),
            Source(
                "usda-nass-census-aquaculture",
                "USDA National Agricultural Statistics Service (NASS)",
                "Census of Aquaculture",
                [미국농어업경영체정보분야Codes.Aquaculture],
                미국농어업경영체정보기록유형Codes.AggregateStatistics,
                미국농어업경영체정보공개범위Codes.PublicAggregateOnly,
                "미국 전국·주별 집계",
                [미국농어업경영체정보접근방식Codes.Api,
                    미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.IntegratedAggregateApi,
                "https://www.nass.usda.gov/Surveys/Guide_to_NASS_Surveys/Census_of_Aquaculture/",
                "https://quickstats.nass.usda.gov/api",
                "농업총조사 특별조사 주기",
                canDiscoverBusinesses: false,
                canConfirmProgramStatus: false,
                containsPotentialPersonalData: false,
                ["양식장 수 집계", "품종별 생산·판매 집계", "생산 방식·수면 면적 집계"],
                ["양식 생산지역·품목 규모 분석"],
                ["개별 양식장·운영자 식별", "비공개 표식을 수치로 임의 변환"],
                ["개별 응답은 비공개이며 NASS는 표 형태의 집계만 공개합니다."],
                "USDA NASS Census of Aquaculture"),
            Source(
                "usda-organic-integrity",
                "USDA Agricultural Marketing Service National Organic Program",
                "Organic INTEGRITY Database",
                [미국농어업경영체정보분야Codes.Agriculture,
                    미국농어업경영체정보분야Codes.Aquaculture,
                    미국농어업경영체정보분야Codes.LocalFoodDistribution],
                미국농어업경영체정보기록유형Codes.CertifiedOperationDirectory,
                미국농어업경영체정보공개범위Codes.PublicBusinessDirectory,
                "USDA NOP 인증 운영체의 국제 명부",
                [미국농어업경영체정보접근방식Codes.DynamicSearch,
                    미국농어업경영체정보접근방식Codes.WebDirectory],
                미국농어업경영체정보통합상태Codes.OfficialLookupOnly,
                "https://www.ams.usda.gov/services/organic-certification/certifiers-inspectors",
                "https://organic.ams.usda.gov/integrity/",
                "인증기관 갱신",
                canDiscoverBusinesses: true,
                canConfirmProgramStatus: true,
                containsPotentialPersonalData: true,
                ["운영체명", "NOP ID", "인증기관", "인증 상태·범위", "인증 제품", "사업 유형"],
                ["유기농 생산·취급 후보 발견", "최신 유기농 인증 상태 대조"],
                ["유기농 인증을 일반 영업·수출입 허가로 해석", "공개 담당자 정보를 자동 초대·영업에 사용"],
                ["유기농 인증 프로그램 명부이며 미국 농업경영체 전체 명부가 아닙니다."],
                "USDA National Organic Program Certifiers and Inspectors")
        }
        .OrderBy(item => item.DisplayName, StringComparer.OrdinalIgnoreCase)
        .ToArray());

    private static 미국농어업경영체정보원천항목 Source(
        string sourceKey,
        string agencyName,
        string displayName,
        IReadOnlyList<string> sectorCodes,
        string recordTypeCode,
        string publicAccessCode,
        string geographicScope,
        IReadOnlyList<string> accessModeCodes,
        string integrationStatusCode,
        string officialUrl,
        string? machineReadableAccessUrl,
        string updateCycle,
        bool canDiscoverBusinesses,
        bool canConfirmProgramStatus,
        bool containsPotentialPersonalData,
        IReadOnlyList<string> publicFieldExamples,
        IReadOnlyList<string> allowedPlatformUses,
        IReadOnlyList<string> prohibitedPlatformUses,
        IReadOnlyList<string> limitations,
        string sourceTitle)
        => new()
        {
            SourceKey = sourceKey,
            AgencyName = agencyName,
            DisplayName = displayName,
            SectorCodes = sectorCodes,
            RecordTypeCode = recordTypeCode,
            PublicAccessCode = publicAccessCode,
            GeographicScope = geographicScope,
            AccessModeCodes = accessModeCodes,
            IntegrationStatusCode = integrationStatusCode,
            OfficialUrl = officialUrl,
            MachineReadableAccessUrl = machineReadableAccessUrl,
            UpdateCycle = updateCycle,
            CanDiscoverBusinesses = canDiscoverBusinesses,
            CanConfirmProgramStatus = canConfirmProgramStatus,
            CanVerifyTransactionAuthority = false,
            CanAutoInvite = false,
            CanAutoSelectForOperations = false,
            ContainsPotentialPersonalData = containsPotentialPersonalData,
            IsComprehensiveRegistry = false,
            RequiresLiveRecheck = true,
            PublicFieldExamples = publicFieldExamples,
            AllowedPlatformUses = allowedPlatformUses,
            ProhibitedPlatformUses = prohibitedPlatformUses,
            Limitations = limitations,
            Evidence =
            [
                new 미국농어업경영체정보원천증거
                {
                    SourceTitle = sourceTitle,
                    SourceUrl = officialUrl,
                    ReviewedOn = SnapshotReviewedOn
                }
            ]
        };
}
