// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Infrastructure.Persistence.PublicData;

#nullable disable

namespace Ssalddel.Infrastructure.Persistence.PublicData.Migrations
{
    [DbContext(typeof(PublicDataIngestionDbContext))]
    [Migration("20260912104457_AddAdministrativeDongDioramaDisplayLedgers")]
    partial class AddAdministrativeDongDioramaDisplayLedgers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물공개사업장Aggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AggregateHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("BuildingRecordId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ClosedBusinessCount")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OpenBusinessCount")
                        .HasColumnType("int");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SuspendedBusinessCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalBusinessCount")
                        .HasColumnType("int");

                    b.Property<int>("UnresolvedStatusCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingRecordId", "SourceRevision", "RuleRevision")
                        .IsUnique();

                    b.ToTable("public_building_business_aggregates", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물대장표제부Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("AboveGroundFloorCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("BuildingAreaSquareMeters")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DongName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("EvidenceSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("HeightMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("LandLot")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LegalDongCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MainPurposeCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("MainPurposeName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NormalizedRoadAddressKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("OfficialBuildingCoveragePercent")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("OfficialFloorAreaRatioPercent")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("RegisterKindCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RegisterManagementPk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RegisterTypeCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RoadAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SigunguCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("SiteAreaSquareMeters")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StructureCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StructureName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TotalFloorAreaSquareMeters")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<int?>("UndergroundFloorCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterManagementPk", "SourceRevision")
                        .IsUnique();

                    b.HasIndex("SigunguCode", "LegalDongCode", "ValidToUtc");

                    b.ToTable("public_building_register_titles", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물시각구성계획", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("LOD등급Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("LodTierCode");

                    b.Property<Guid>("건축물형태ProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("BuildingMassingProfileId");

                    b.Property<string>("계획HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("PlanHashSha256");

                    b.Property<string>("규칙개정번호")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("RuleRevision");

                    b.Property<int>("기준층수")
                        .HasColumnType("int")
                        .HasColumnName("PresentationFloorCount");

                    b.Property<string>("대지점유등급Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("SiteCoverageTierCode");

                    b.Property<DateTimeOffset>("생성시각Utc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("GeneratedAtUtc");

                    b.Property<string>("시각FamilyCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("VisualFamilyCode");

                    b.Property<string>("주변여백등급Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("SurroundingSpaceTierCode");

                    b.Property<int>("중간층반복수")
                        .HasColumnType("int")
                        .HasColumnName("MiddleFloorRepeatCount");

                    b.Property<bool>("표현전용")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PresentationOnly");

                    b.HasKey("Id");

                    b.HasIndex("건축물형태ProfileId", "규칙개정번호")
                        .IsUnique();

                    b.ToTable("public_building_visual_composition_plans", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물용도CategoryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignmentMethodCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("BuildingRecordId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("ClassifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceMainPurposeCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SourceMainPurposeName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode", "RuleRevision");

                    b.HasIndex("BuildingRecordId", "RuleRevision", "IsPrimary")
                        .IsUnique();

                    b.ToTable("public_building_category_assignments", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물용도CategoryDefinition", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DescriptionKo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DisplayNameKo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("PresentationEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("WorldRoleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("CategoryCode");

                    b.ToTable("public_building_category_catalog", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryCode = "residential",
                            DescriptionKo = "단독·공동주택 등 사람이 거주하는 건축물",
                            DisplayNameKo = "주거",
                            PresentationEligible = true,
                            SortOrder = 10,
                            WorldRoleCode = "settlement"
                        },
                        new
                        {
                            CategoryCode = "agriculture",
                            DescriptionKo = "동물·식물 관련 시설 등 농업 생산을 지원하는 건축물",
                            DisplayNameKo = "농업",
                            PresentationEligible = true,
                            SortOrder = 20,
                            WorldRoleCode = "farm"
                        },
                        new
                        {
                            CategoryCode = "logistics-storage",
                            DescriptionKo = "창고시설 등 보관·적재와 관계되는 건축물",
                            DisplayNameKo = "물류·창고",
                            PresentationEligible = true,
                            SortOrder = 30,
                            WorldRoleCode = "hub"
                        },
                        new
                        {
                            CategoryCode = "commercial",
                            DescriptionKo = "근린생활·판매시설 등 생활권 상업 건축물",
                            DisplayNameKo = "상업·생활",
                            PresentationEligible = true,
                            SortOrder = 40,
                            WorldRoleCode = "town"
                        },
                        new
                        {
                            CategoryCode = "business-office",
                            DescriptionKo = "업무시설 등 사무 기능의 건축물",
                            DisplayNameKo = "업무",
                            PresentationEligible = true,
                            SortOrder = 50,
                            WorldRoleCode = "town"
                        },
                        new
                        {
                            CategoryCode = "public-community",
                            DescriptionKo = "공공·안전·공동체 기능으로 검토할 건축물",
                            DisplayNameKo = "공공·공동체",
                            PresentationEligible = true,
                            SortOrder = 60,
                            WorldRoleCode = "civic"
                        },
                        new
                        {
                            CategoryCode = "industrial",
                            DescriptionKo = "공장 등 제조·산업 기능의 건축물",
                            DisplayNameKo = "산업",
                            PresentationEligible = true,
                            SortOrder = 70,
                            WorldRoleCode = "industrial"
                        },
                        new
                        {
                            CategoryCode = "education-research",
                            DescriptionKo = "교육연구시설",
                            DisplayNameKo = "교육·연구",
                            PresentationEligible = true,
                            SortOrder = 80,
                            WorldRoleCode = "civic"
                        },
                        new
                        {
                            CategoryCode = "medical-welfare",
                            DescriptionKo = "의료시설과 노유자시설",
                            DisplayNameKo = "의료·복지",
                            PresentationEligible = true,
                            SortOrder = 90,
                            WorldRoleCode = "civic"
                        },
                        new
                        {
                            CategoryCode = "culture-tourism",
                            DescriptionKo = "문화·집회·숙박·관광·운동 관련 건축물",
                            DisplayNameKo = "문화·관광",
                            PresentationEligible = true,
                            SortOrder = 100,
                            WorldRoleCode = "town"
                        },
                        new
                        {
                            CategoryCode = "transport",
                            DescriptionKo = "운수시설과 자동차 관련 시설",
                            DisplayNameKo = "교통",
                            PresentationEligible = true,
                            SortOrder = 110,
                            WorldRoleCode = "transport"
                        },
                        new
                        {
                            CategoryCode = "utility-infrastructure",
                            DescriptionKo = "발전·방송통신·자원순환·위험물 처리 관련 건축물",
                            DisplayNameKo = "기반시설",
                            PresentationEligible = true,
                            SortOrder = 120,
                            WorldRoleCode = "infrastructure"
                        },
                        new
                        {
                            CategoryCode = "religious",
                            DescriptionKo = "종교시설",
                            DisplayNameKo = "종교",
                            PresentationEligible = true,
                            SortOrder = 130,
                            WorldRoleCode = "settlement"
                        },
                        new
                        {
                            CategoryCode = "other",
                            DescriptionKo = "공식 주용도는 있으나 현재 규칙에 대응하지 않는 건축물",
                            DisplayNameKo = "기타",
                            PresentationEligible = false,
                            SortOrder = 900,
                            WorldRoleCode = "generic"
                        },
                        new
                        {
                            CategoryCode = "unresolved",
                            DescriptionKo = "공식 주용도가 없거나 행정동 배정·분류가 해결되지 않은 건축물",
                            DisplayNameKo = "미분류",
                            PresentationEligible = false,
                            SortOrder = 999,
                            WorldRoleCode = "unresolved"
                        });
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물행정구역Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdministrativeRegionStableId")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("AssignmentMethodCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("BuildingRecordId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfidenceCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LegalRegionStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceVintage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeRegionStableId", "SourceVintage");

                    b.HasIndex("BuildingRecordId", "RuleRevision")
                        .IsUnique();

                    b.ToTable("public_building_region_assignments", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물형태Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ProfileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("건물바닥면적등급Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("FootprintTierCode");

                    b.Property<decimal?>("건축면적SquareMeters")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("BuildingAreaSquareMeters");

                    b.Property<Guid>("건축물RecordId")
                        .HasColumnType("char(36)")
                        .HasColumnName("BuildingRecordId");

                    b.Property<decimal?>("공식건폐율Percent")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("OfficialBuildingCoveragePercent");

                    b.Property<decimal?>("공식용적률Percent")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("OfficialFloorAreaRatioPercent");

                    b.Property<int?>("관측지상층수")
                        .HasColumnType("int")
                        .HasColumnName("ObservedAboveGroundFloorCount");

                    b.Property<string>("규칙개정번호")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("RuleRevision");

                    b.Property<string>("근거종류Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("EvidenceKindCode");

                    b.Property<decimal?>("높이Meters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("HeightMeters");

                    b.Property<string>("높이등급Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("HeightTierCode");

                    b.Property<decimal?>("단순건폐비율Percent")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("SimpleBuildingToSiteRatioPercent");

                    b.Property<decimal?>("단순연면적대지비율Percent")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("SimpleGrossFloorToSiteRatioPercent");

                    b.Property<decimal?>("대지면적SquareMeters")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("SiteAreaSquareMeters");

                    b.Property<string>("밀도등급Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("DensityTierCode");

                    b.Property<DateTimeOffset>("생성시각Utc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("GeneratedAtUtc");

                    b.Property<decimal?>("연면적SquareMeters")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("TotalFloorAreaSquareMeters");

                    b.Property<int?>("추정지상층수")
                        .HasColumnType("int")
                        .HasColumnName("EstimatedAboveGroundFloorCount");

                    b.Property<decimal?>("추정층고Meters")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("EstimatedFloorHeightMeters");

                    b.Property<int>("표현지상층수")
                        .HasColumnType("int")
                        .HasColumnName("PresentationAboveGroundFloorCount");

                    b.HasKey("Id");

                    b.HasIndex("건축물RecordId", "규칙개정번호")
                        .IsUnique();

                    b.ToTable("public_building_massing_profiles", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.공개사업장건축물Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignmentMethodCode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("AssignmentStatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<Guid?>("BuildingRecordId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessRecordId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CandidateBuildingCount")
                        .HasColumnType("int");

                    b.Property<string>("ConfidenceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingRecordId", "AssignmentStatusCode");

                    b.HasIndex("BusinessRecordId", "RuleRevision")
                        .IsUnique();

                    b.ToTable("public_business_building_assignments", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.공개인허가사업장Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("BusinessStatusCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("BusinessStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BusinessTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("ClosureDate")
                        .HasColumnType("date");

                    b.Property<string>("DetailedStatusCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("DetailedStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("EvidenceSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<string>("LicenseCategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("LicenseDate")
                        .HasColumnType("date");

                    b.Property<string>("LotAddress")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("ManagementNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("NormalizedRoadAddressKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OpenServiceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("OpenServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RoadAddress")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("SourceCoordinateReferenceSystem")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("SourceCoordinateX")
                        .HasPrecision(20, 8)
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("SourceCoordinateY")
                        .HasPrecision(20, 8)
                        .HasColumnType("decimal(20,8)");

                    b.Property<string>("SourceDatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset?>("SourceLastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessStatusCode", "SourceRevision");

                    b.HasIndex("NormalizedRoadAddressKey", "SourceRevision");

                    b.HasIndex("SourceId", "OpenServiceId", "ManagementNumber", "SourceRevision")
                        .IsUnique();

                    b.ToTable("public_licensed_business_records", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.지역디오라마후원Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<Guid>("BusinessDisplayClaimId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CampaignStableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("DetailCardText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedByUserStableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ReviewReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserStableId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignStableId")
                        .IsUnique();

                    b.HasIndex("BusinessDisplayClaimId", "StatusCode", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("regional_diorama_sponsorship_campaigns", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.지역사업장표시Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdministrativeRegionStableId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ClaimStableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid>("PublicBusinessRecordId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedByUserStableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("RequestedDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ReviewReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserStableId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SemanticPlaceStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimStableId")
                        .IsUnique();

                    b.HasIndex("AdministrativeRegionStableId", "StatusCode");

                    b.HasIndex("PublicBusinessRecordId", "StatusCode");

                    b.ToTable("regional_business_display_claims", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.행정동건축물CategoryAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdministrativeRegionStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("AggregateHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("BuildingAreaSquareMeters")
                        .HasPrecision(24, 4)
                        .HasColumnType("decimal(24,4)");

                    b.Property<long>("BuildingCount")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GeometryLinkedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("NamedBuildingCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceVintage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TotalFloorAreaSquareMeters")
                        .HasPrecision(24, 4)
                        .HasColumnType("decimal(24,4)");

                    b.Property<long>("UnresolvedBuildingCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("AdministrativeRegionStableId", "SourceVintage", "CategoryCode", "RuleRevision")
                        .IsUnique();

                    b.ToTable("public_administrative_building_category_aggregates", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터RawSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset?>("EvidenceAsOfUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FirstCollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StorageContainer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("StorageObjectName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("FirstCollectionRunId");

                    b.HasIndex("SourceId", "DatasetId", "ContentHashSha256")
                        .IsUnique();

                    b.ToTable("public_data_raw_snapshots", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터수집Run", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ErrorSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ExistingCount")
                        .HasColumnType("int");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<int>("NormalizedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<string>("RunKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunKey")
                        .IsUnique();

                    b.HasIndex("SourceId", "DatasetId", "StartedAtUtc");

                    b.ToTable("public_data_ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터정규화Record", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("DimensionKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("EvidenceAsOfUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LimitationCode")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("QualityCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long>("RawSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RegionStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SpatialPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("TemporalPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("TextValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RawSnapshotId");

                    b.HasIndex("RecordKey")
                        .IsUnique();

                    b.HasIndex("RegionStableId", "MetricCode", "EvidenceAsOfUtc");

                    b.ToTable("public_data_normalized_records", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부지역CodeMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalRegionCode")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("MappingRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RegionStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SpatialPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "ExternalRegionCode")
                        .IsUnique();

                    b.ToTable("public_data_region_mappings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1001L,
                            ExternalRegionCode = "KOR",
                            MappingRevision = "iso3166-1-alpha3-v2026-08",
                            RegionStableId = "country:kr",
                            SourceId = "world-bank-indicators",
                            SpatialPrecisionCode = "country"
                        },
                        new
                        {
                            Id = -1002L,
                            ExternalRegionCode = "USA",
                            MappingRevision = "iso3166-1-alpha3-v2026-08",
                            RegionStableId = "country:us",
                            SourceId = "world-bank-indicators",
                            SpatialPrecisionCode = "country"
                        },
                        new
                        {
                            Id = -1003L,
                            ExternalRegionCode = "CHN",
                            MappingRevision = "iso3166-1-alpha3-v2026-08",
                            RegionStableId = "country:cn",
                            SourceId = "world-bank-indicators",
                            SpatialPrecisionCode = "country"
                        });
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물공개사업장Aggregate", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물대장표제부Record", "BuildingRecord")
                        .WithMany()
                        .HasForeignKey("BuildingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingRecord");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물시각구성계획", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물형태Profile", "건축물형태Profile")
                        .WithMany()
                        .HasForeignKey("건축물형태ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("건축물형태Profile");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물용도CategoryAssignment", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물대장표제부Record", "BuildingRecord")
                        .WithMany()
                        .HasForeignKey("BuildingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물용도CategoryDefinition", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingRecord");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물행정구역Assignment", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물대장표제부Record", "BuildingRecord")
                        .WithMany()
                        .HasForeignKey("BuildingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingRecord");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.건축물형태Profile", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물대장표제부Record", "건축물Record")
                        .WithMany()
                        .HasForeignKey("건축물RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("건축물Record");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.공개사업장건축물Assignment", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물대장표제부Record", "BuildingRecord")
                        .WithMany()
                        .HasForeignKey("BuildingRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ssalddel.Domain.PublicData.Korea.공개인허가사업장Record", "BusinessRecord")
                        .WithMany()
                        .HasForeignKey("BusinessRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingRecord");

                    b.Navigation("BusinessRecord");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.지역디오라마후원Campaign", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.지역사업장표시Claim", "BusinessDisplayClaim")
                        .WithMany()
                        .HasForeignKey("BusinessDisplayClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessDisplayClaim");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.지역사업장표시Claim", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.공개인허가사업장Record", "PublicBusinessRecord")
                        .WithMany()
                        .HasForeignKey("PublicBusinessRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublicBusinessRecord");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.Korea.행정동건축물CategoryAggregate", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.Korea.건축물용도CategoryDefinition", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터RawSnapshot", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.외부데이터수집Run", "FirstCollectionRun")
                        .WithMany()
                        .HasForeignKey("FirstCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstCollectionRun");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터정규화Record", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.외부데이터RawSnapshot", "RawSnapshot")
                        .WithMany()
                        .HasForeignKey("RawSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
