// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Simulation.Persistence;

#nullable disable

namespace Ssalddel.Simulation.Persistence.Migrations.SimulationSession
{
    [DbContext(typeof(SimulationSessionDbContext))]
    [Migration("20260925133313_AddFranchiseSupplyChainProjectionFoundation")]
    partial class AddFranchiseSupplyChainProjectionFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationOnlineWorld상태사본Entity", b =>
                {
                    b.Property<string>("CheckpointStableId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("상태사본고유식별자");

                    b.Property<string>("CheckpointHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("상태사본SHA256");

                    b.Property<string>("CheckpointJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태사본JSON");

                    b.Property<long>("DirectoryRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("세계Directory개정번호");

                    b.Property<string>("SchemaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("스키마코드");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.HasKey("CheckpointStableId");

                    b.ToTable("시뮬레이션온라인세계_상태사본", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationSession저장자료Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommandCount")
                        .HasColumnType("int")
                        .HasColumnName("명령기록수");

                    b.Property<string>("PackageJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("저장자료JSON");

                    b.Property<string>("ReplayHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("재생SHA256");

                    b.Property<string>("ReplayHashAlgorithmCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("재생Hash알고리즘코드");

                    b.Property<string>("SaveStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("저장자료고유식별자");

                    b.Property<long>("SavedWorldRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("저장World개정번호");

                    b.Property<int>("SavedWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("저장WorldTick");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("스키마버전");

                    b.Property<string>("SessionStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.HasKey("Id");

                    b.HasIndex("SaveStableId")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "SavedWorldRevision");

                    b.ToTable("시뮬레이션세션_저장자료", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationSession접근원장Entity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자");

                    b.Property<string>("AccessRoleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("접근역할코드");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("개정번호");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("로그인주체식별자");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("수정시각UTC");

                    b.HasKey("SessionStableId");

                    b.HasIndex("SubjectId", "SessionStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션세션_접근원장", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈공급망ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<int>("AsOfWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("기준WorldTick");

                    b.Property<string>("DataRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("자료개정번호");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<bool>("IsOperationalState")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("운영상태여부");

                    b.Property<bool>("IsReadOnlyProjection")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("읽기전용Projection여부");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("합성자료여부");

                    b.Property<string>("ModeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("실행모드코드");

                    b.Property<long>("ProjectionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("Projection개정번호");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("규칙개정번호");

                    b.Property<string>("ScenarioStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Scenario고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ScenarioStableId"), "ascii");

                    b.Property<string>("SourceKindCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("자료종류코드");

                    b.Property<long>("SourceSessionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본세션개정번호");

                    b.Property<string>("SourceStableIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("출처고유식별자목록JSON");

                    b.Property<string>("StateAuthorityCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태권위코드");

                    b.Property<string>("StatePayloadHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("상태PayloadSHA256");

                    b.HasKey("SessionStableId", "NetworkStableId");

                    b.HasIndex("SessionStableId", "ScenarioStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈공급망Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈공급망Projection_읽기전용Simulation", "`실행모드코드` = 'Simulation' AND `상태권위코드` = 'SessionAggregate' AND `합성자료여부` = 1 AND `운영상태여부` = 0 AND `읽기전용Projection여부` = 1");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈공급자ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("SupplierStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급자고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SupplierStableId"), "ascii");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("표시명");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("SupplierKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("공급자키")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("SupplierKindCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("공급자종류코드");

                    b.HasKey("SessionStableId", "NetworkStableId", "SupplierStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "SupplierKey")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈공급자Projection", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("StoreStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StoreStableId"), "ascii");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("표시명");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("SemanticPlaceStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("의미장소고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SemanticPlaceStableId"), "ascii");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("매장코드")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("SessionStableId", "NetworkStableId", "StoreStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "StoreCode")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈매장Projection", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("OfferStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장공급안고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OfferStableId"), "ascii");

                    b.Property<string>("CommercialFlowModelCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("상업흐름모형코드");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("통화코드");

                    b.Property<int>("EffectiveFromWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("시작WorldTick");

                    b.Property<int?>("EffectiveUntilWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("종료WorldTick");

                    b.Property<string>("FulfillmentModelCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("이행모형코드");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<string>("OfferDocumentVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("공급안문서판본");

                    b.Property<string>("OfferNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("공급안번호")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.HasKey("SessionStableId", "NetworkStableId", "OfferStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferNumber")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈매장공급안Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈매장공급안Projection_유효기간", "`종료WorldTick` IS NULL OR `종료WorldTick` >= `시작WorldTick`");

                            t.HasCheckConstraint("CK_프랜차이즈매장공급안Projection_첫Slice", "`상업흐름모형코드` = 'HeadquartersResale' AND `이행모형코드` = 'HeadquartersFleet'");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안품목ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("OfferItemStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장공급안품목고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OfferItemStableId"), "ascii");

                    b.Property<string>("ConversionRuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("단위변환규칙개정번호");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("품목명");

                    b.Property<decimal?>("MaximumOrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최대발주수량");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최소발주수량");

                    b.Property<string>("OfferStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장공급안고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OfferStableId"), "ascii");

                    b.Property<string>("OrderUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("발주단위코드");

                    b.Property<decimal>("PackageContentQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("포장내용수량");

                    b.Property<string>("PackageContentUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("포장내용단위코드");

                    b.Property<string>("ProductStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("상품고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ProductStableId"), "ascii");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("SourceContractItemStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본조달계약품목고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceContractItemStableId"), "ascii");

                    b.Property<string>("SourceContractStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본조달계약고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceContractStableId"), "ascii");

                    b.Property<string>("SourceStableIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("출처고유식별자목록JSON");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("StorageConditionCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("보관조건코드");

                    b.Property<string>("StoreSku")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("매장공급SKU")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("단가");

                    b.HasKey("SessionStableId", "NetworkStableId", "OfferItemStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "OfferStableId", "StoreSku")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "SourceContractStableId", "SourceContractItemStableId");

                    b.ToTable("시뮬레이션_프랜차이즈매장공급안품목Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈매장공급안품목Projection_수량가격", "`포장내용수량` > 0 AND `단가` >= 0 AND `최소발주수량` > 0 AND (`최대발주수량` IS NULL OR `최대발주수량` >= `최소발주수량`)");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장발주ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("OrderStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장발주고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OrderStableId"), "ascii");

                    b.Property<string>("ClientRequestStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("요청고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ClientRequestStableId"), "ascii");

                    b.Property<string>("CommercialFlowModelCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("상업흐름모형코드사본");

                    b.Property<int>("CreatedWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("생성WorldTick");

                    b.Property<string>("CurrencyCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("통화코드사본");

                    b.Property<string>("DeliverySiteStableIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("납품지고유식별자사본")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DeliverySiteStableIdSnapshot"), "ascii");

                    b.Property<string>("FulfillmentModelCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("이행모형코드사본");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<string>("OfferDocumentVersionSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("공급안문서판본사본");

                    b.Property<string>("OfferStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장공급안고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OfferStableId"), "ascii");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("발주번호")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("RequestPayloadHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("요청PayloadSHA256");

                    b.Property<int>("RequestedDeliveryWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("요청납품WorldTick");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("SellerHeadquartersStableIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("판매본부고유식별자사본")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SellerHeadquartersStableIdSnapshot"), "ascii");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("StoreMembershipStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장소속고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StoreMembershipStableId"), "ascii");

                    b.Property<string>("StoreStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StoreStableId"), "ascii");

                    b.Property<int?>("SubmittedWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("제출WorldTick");

                    b.Property<decimal>("TotalAmountSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("발주합계금액사본");

                    b.HasKey("SessionStableId", "NetworkStableId", "OrderStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "StoreMembershipStableId", "ClientRequestStableId")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "NetworkStableId", "StoreMembershipStableId", "OrderNumber")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "StoreMembershipStableId", "StoreStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "OfferStableId", "StatusCode", "RequestedDeliveryWorldTick");

                    b.ToTable("시뮬레이션_프랜차이즈매장발주Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈매장발주Projection_합계", "`발주합계금액사본` >= 0");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장발주품목ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("OrderLineStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장발주품목고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OrderLineStableId"), "ascii");

                    b.Property<decimal?>("AcceptedOrderUnitQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("수락발주단위수량");

                    b.Property<string>("ConversionRuleRevisionSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("단위변환규칙개정번호사본");

                    b.Property<string>("CurrencyCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("통화코드사본");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("품목명사본");

                    b.Property<decimal>("LineAmountSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("품목금액사본");

                    b.Property<string>("OfferItemStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장공급안품목고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OfferItemStableId"), "ascii");

                    b.Property<string>("OfferStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장공급안고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OfferStableId"), "ascii");

                    b.Property<string>("OrderStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장발주고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OrderStableId"), "ascii");

                    b.Property<string>("OrderUnitCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("발주단위코드사본");

                    b.Property<decimal>("PackageContentQuantitySnapshot")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("포장내용수량사본");

                    b.Property<string>("PackageContentUnitCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("포장내용단위코드사본");

                    b.Property<string>("ProductStableIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("상품고유식별자사본")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ProductStableIdSnapshot"), "ascii");

                    b.Property<decimal>("RequestedContentQuantitySnapshot")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("요청내용수량사본");

                    b.Property<decimal>("RequestedOrderUnitQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("요청발주단위수량");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("StoreSkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("매장공급SKU사본");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("단가사본");

                    b.HasKey("SessionStableId", "NetworkStableId", "OrderLineStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "OrderStableId", "OfferItemStableId")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId", "OfferItemStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId", "OrderStableId")
                        .HasDatabaseName("IX_시뮬레이션_프랜차이즈매장발주품목Projection_세션고유식별자_공급망고유식별자_본부고유식별자_매장공급안고~1");

                    b.ToTable("시뮬레이션_프랜차이즈매장발주품목Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈매장발주품목Projection_수량가격", "`요청발주단위수량` > 0 AND `요청내용수량사본` > 0 AND (`수락발주단위수량` IS NULL OR (`수락발주단위수량` >= 0 AND `수락발주단위수량` <= `요청발주단위수량`)) AND `품목금액사본` >= 0");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장소속ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("MembershipStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장소속고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MembershipStableId"), "ascii");

                    b.Property<int>("EffectiveFromWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("시작WorldTick");

                    b.Property<int?>("EffectiveUntilWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("종료WorldTick");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("StoreStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("매장고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StoreStableId"), "ascii");

                    b.HasKey("SessionStableId", "NetworkStableId", "MembershipStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "StoreStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "StoreStableId", "EffectiveFromWorldTick")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈매장소속Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈매장소속Projection_유효기간", "`종료WorldTick` IS NULL OR `종료WorldTick` >= `시작WorldTick`");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈본부ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("HeadquartersStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("표시명");

                    b.Property<string>("HeadquartersCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("본부코드")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.HasKey("SessionStableId", "NetworkStableId", "HeadquartersStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersCode")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈본부Projection", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈조달계약ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("ContractStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("조달계약고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContractStableId"), "ascii");

                    b.Property<string>("ContractDocumentVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("계약문서판본");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("계약번호")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("통화코드");

                    b.Property<int>("EffectiveFromWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("시작WorldTick");

                    b.Property<int?>("EffectiveUntilWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("종료WorldTick");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("SupplierStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급자고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SupplierStableId"), "ascii");

                    b.HasKey("SessionStableId", "NetworkStableId", "ContractStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "HeadquartersStableId", "ContractNumber")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "NetworkStableId", "SupplierStableId", "StatusCode");

                    b.ToTable("시뮬레이션_프랜차이즈조달계약Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈조달계약Projection_유효기간", "`종료WorldTick` IS NULL OR `종료WorldTick` >= `시작WorldTick`");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈조달계약품목ProjectionEntity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionStableId"), "ascii");

                    b.Property<string>("NetworkStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공급망고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkStableId"), "ascii");

                    b.Property<string>("ContractItemStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("조달계약품목고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContractItemStableId"), "ascii");

                    b.Property<string>("ContractStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("조달계약고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContractStableId"), "ascii");

                    b.Property<string>("ConversionRuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("단위변환규칙개정번호");

                    b.Property<string>("HeadquartersStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("본부고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HeadquartersStableId"), "ascii");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("품목명");

                    b.Property<decimal?>("MaximumOrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최대발주수량");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최소발주수량");

                    b.Property<string>("OrderUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("발주단위코드");

                    b.Property<decimal>("PackageContentQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("포장내용수량");

                    b.Property<string>("PackageContentUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("포장내용단위코드");

                    b.Property<string>("ProductStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("상품고유식별자")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ProductStableId"), "ascii");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("SourceStableIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("출처고유식별자목록JSON");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("상태코드");

                    b.Property<string>("StorageConditionCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("보관조건코드");

                    b.Property<string>("SupplierSku")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("공급자SKU")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("단가");

                    b.HasKey("SessionStableId", "NetworkStableId", "ContractItemStableId");

                    b.HasIndex("SessionStableId", "NetworkStableId", "ContractStableId", "SupplierSku")
                        .IsUnique();

                    b.ToTable("시뮬레이션_프랜차이즈조달계약품목Projection", null, t =>
                        {
                            t.HasCheckConstraint("CK_프랜차이즈조달계약품목Projection_수량가격", "`포장내용수량` > 0 AND `단가` >= 0 AND `최소발주수량` > 0 AND (`최대발주수량` IS NULL OR `최대발주수량` >= `최소발주수량`)");
                        });
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈공급자ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈공급망ProjectionEntity", "Network")
                        .WithMany("Suppliers")
                        .HasForeignKey("SessionStableId", "NetworkStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈공급망ProjectionEntity", "Network")
                        .WithMany("Stores")
                        .HasForeignKey("SessionStableId", "NetworkStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈본부ProjectionEntity", "Headquarters")
                        .WithMany("StoreSupplyOffers")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Headquarters");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안품목ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안ProjectionEntity", "Offer")
                        .WithMany("Items")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈조달계약품목ProjectionEntity", "SourceContractItem")
                        .WithMany("StoreOfferItems")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "SourceContractStableId", "SourceContractItemStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "ContractStableId", "ContractItemStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("SourceContractItem");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장발주ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안ProjectionEntity", "Offer")
                        .WithMany("Orders")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈매장소속ProjectionEntity", "StoreMembership")
                        .WithMany("Orders")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "StoreMembershipStableId", "StoreStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "MembershipStableId", "StoreStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("StoreMembership");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장발주품목ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안품목ProjectionEntity", "OfferItem")
                        .WithMany("OrderLines")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId", "OfferItemStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId", "OfferItemStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈매장발주ProjectionEntity", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId", "OrderStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "OfferStableId", "OrderStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfferItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장소속ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈본부ProjectionEntity", "Headquarters")
                        .WithMany("StoreMemberships")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈매장ProjectionEntity", "Store")
                        .WithMany("Memberships")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "StoreStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Headquarters");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈본부ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈공급망ProjectionEntity", "Network")
                        .WithMany("Headquarters")
                        .HasForeignKey("SessionStableId", "NetworkStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈조달계약ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈본부ProjectionEntity", "Headquarters")
                        .WithMany("SourcingAgreements")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈공급자ProjectionEntity", "Supplier")
                        .WithMany("SourcingAgreements")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "SupplierStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Headquarters");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈조달계약품목ProjectionEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.프랜차이즈조달계약ProjectionEntity", "Contract")
                        .WithMany("Items")
                        .HasForeignKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "ContractStableId")
                        .HasPrincipalKey("SessionStableId", "NetworkStableId", "HeadquartersStableId", "ContractStableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈공급망ProjectionEntity", b =>
                {
                    b.Navigation("Headquarters");

                    b.Navigation("Stores");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈공급자ProjectionEntity", b =>
                {
                    b.Navigation("SourcingAgreements");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장ProjectionEntity", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안ProjectionEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장공급안품목ProjectionEntity", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장발주ProjectionEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈매장소속ProjectionEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈본부ProjectionEntity", b =>
                {
                    b.Navigation("SourcingAgreements");

                    b.Navigation("StoreMemberships");

                    b.Navigation("StoreSupplyOffers");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈조달계약ProjectionEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.프랜차이즈조달계약품목ProjectionEntity", b =>
                {
                    b.Navigation("StoreOfferItems");
                });
#pragma warning restore 612, 618
        }
    }
}
