// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Simulation.Persistence;

#nullable disable

namespace Ssalddel.Simulation.Persistence.Migrations.SimulationSession
{
    [DbContext(typeof(SimulationSessionDbContext))]
    partial class SimulationSessionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationOnlineWorld상태사본Entity", b =>
                {
                    b.Property<string>("CheckpointStableId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("상태사본고유식별자");

                    b.Property<string>("CheckpointHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("상태사본SHA256");

                    b.Property<string>("CheckpointJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태사본JSON");

                    b.Property<long>("DirectoryRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("세계Directory개정번호");

                    b.Property<string>("SchemaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("스키마코드");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.HasKey("CheckpointStableId");

                    b.ToTable("시뮬레이션온라인세계_상태사본", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationSession저장자료Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommandCount")
                        .HasColumnType("int")
                        .HasColumnName("명령기록수");

                    b.Property<string>("PackageJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("저장자료JSON");

                    b.Property<string>("ReplayHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("재생SHA256");

                    b.Property<string>("ReplayHashAlgorithmCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("재생Hash알고리즘코드");

                    b.Property<string>("SaveStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("저장자료고유식별자");

                    b.Property<long>("SavedWorldRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("저장World개정번호");

                    b.Property<int>("SavedWorldTick")
                        .HasColumnType("int")
                        .HasColumnName("저장WorldTick");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("스키마버전");

                    b.Property<string>("SessionStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.HasKey("Id");

                    b.HasIndex("SaveStableId")
                        .IsUnique();

                    b.HasIndex("SessionStableId", "SavedWorldRevision");

                    b.ToTable("시뮬레이션세션_저장자료", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationSession접근원장Entity", b =>
                {
                    b.Property<string>("SessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("세션고유식별자");

                    b.Property<string>("AccessRoleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("접근역할코드");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("개정번호");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("로그인주체식별자");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("수정시각UTC");

                    b.HasKey("SessionStableId");

                    b.HasIndex("SubjectId", "SessionStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션세션_접근원장", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
