Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$taskRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$taskArtifact=Join-Path $taskRoot 'artifacts/local/apk-completion-r26'
$taskFood=Get-Content (Join-Path $taskArtifact 'real-ui/verification.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$taskFirstFood=Get-Content (Join-Path $taskArtifact 'real-ui/verification-first-attempt.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$taskSupport=Get-Content (Join-Path $taskArtifact 'real-support-ui/verification.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$taskFirstSupport=Get-Content (Join-Path $taskArtifact 'real-support-ui/verification-first-attempt.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$taskSecondSupport=Get-Content (Join-Path $taskArtifact 'real-support-ui/verification-second-attempt.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$taskGuard=Get-Content (Join-Path $taskArtifact 'actual-api-guards.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$taskServer=Get-Content (Join-Path $taskArtifact 'server/result.json') -Raw -Encoding UTF8 | ConvertFrom-Json
if($taskFood.status -ne 'Completed' -or $taskSupport.status -ne 'Completed' -or $taskGuard.status -ne 'Passed'){throw 'Successful bounded verification missing'}
$taskFoodRows=@($taskFirstFood.results)+@($taskFood.results)
$taskSupportRows=@($taskFirstSupport.rows)+@($taskSecondSupport.rows)+@($taskSupport.rows)
$taskScreens=@(Get-ChildItem (Join-Path $taskArtifact 'real-ui'),(Join-Path $taskArtifact 'real-support-ui'),(Join-Path $taskArtifact 'final-readonly-ui'),(Join-Path $taskArtifact 'final-styled-readonly-ui') -Filter '*.png' -File | Sort-Object FullName | ForEach-Object { @{path=[IO.Path]::GetRelativePath($taskRoot,$_.FullName).Replace('\','/');sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()} })
$taskPaths=@(Get-Content (Join-Path $taskArtifact 'owned-eng-paths.json') -Raw -Encoding UTF8 | ConvertFrom-Json)
$taskUiFiles=@(Get-ChildItem (Join-Path $taskRoot 'Ssalddel.Ui.Common') -Recurse -File | Where-Object { $_.Extension -in '.cs','.razor','.csproj','.css','.js' -and $_.FullName -notmatch '[\\/](bin|obj|artifacts|\.artifacts|\.codex-build)[\\/]' } | Sort-Object FullName)
$taskProductSources=@($taskUiFiles | ForEach-Object { @{path=[IO.Path]::GetRelativePath($taskRoot,$_.FullName).Replace('\','/');sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()} })
$taskSources=@($taskPaths | ForEach-Object { @{path=$_;sha256=(Get-FileHash (Join-Path $taskRoot $_) -Algorithm SHA256).Hash.ToLowerInvariant()} })
$taskEvidence=@{
 schemaVersion='apk-workflow-actual-evidence.r26';generatedAtUtc=[DateTime]::UtcNow.ToString('o');status='Passed';orderNo=$taskFood.orderNo;workStableId=$taskFood.workStableId;caseId=$taskSupport.caseId
 food=@{basis='Actual shared Razor -> production role adapters -> authenticated HTTP -> MySQL';steps=$taskFoodRows;orderCreatedByActualRoleClient=$true;orderCreateUiVerified=$false;completedSharedUiSteps=12;finalUiErrors=0;databaseEvidence='artifacts/local/apk-completion-r26/food-database-state.jsonl';settlementStatus='AwaitingDeductions';grossAmount=2500;netAmount=$null;payoutStatus='NotRequested'}
 support=@{basis='Actual user/admin shared Razor -> production support clients -> authenticated HTTP -> Mongo';steps=$taskSupportRows;finalUiErrors=0;notificationProofs='Two explicitly synthetic notice references; no external message was sent';externalNotificationsSent=$false;finalStatus='reopened';uiSequenceRevision=14;finalRevision=$taskGuard.summary.finalRevision;postUiGuardFixtureRecords=3;databaseEvidence='artifacts/local/apk-completion-r26/support-database-state.json';apiGuards=$taskGuard}
 server=@{endpoint=$taskServer.baseUrl;imageTag=$taskServer.imageTag;imageId=$taskServer.finalImage.imageId;sourceChangedDuringBuild=$taskServer.build.changedDuringBuild;databaseVolumesPreserved=$true;initialImageProof='artifacts/local/apk-completion-r26/server/result-initial-image.json';finalImageProof='artifacts/local/apk-completion-r26/server/result.json'}
 sourceFingerprints=$taskSources;productUiSourceFingerprints=$taskProductSources;screenshots=$taskScreens;productionVerified=$false;physicalDeviceVerified=$false;actualGpsVerified=$false;externalMapVerified=$false;realPaymentVerified=$false;threeDayExpiryRealClockVerified=$false
 selectedInputBoundary=@{originalSourceRoots=@('Ssalddel','Ssalddel.Contracts','Ssalddel.Ui.Common');harnessSourcePaths='artifacts/local/apk-completion-r26/owned-eng-paths.json';serverSelection='All existing .cs/.csproj/.json under Ssalddel and Ssalddel.Contracts excluding bin/obj, listed in server result build hashes';uiSelection='All .cs/.razor/.csproj/.css/.js under Ssalddel.Ui.Common excluding bin/obj/artifacts/.artifacts/.codex-build';generatedOutputIsNotOriginalSource=@('bin','obj','artifacts','.artifacts','.codex-build');binaryProof='artifacts/local/apk-completion-r26/final-preview-binaries.json';supportNoticeInputs='Explicit synthetic references only, no actual external communication proof';fixtureInput='Preserved private fake accounts, menus.json export, fixed 0.250km route and synthetic location';menuProvenance='Preserved public recipe/ingredient snapshot exported for r24 and reused; no new live data query; original sourceUrl/checksum/mappingStatus remain in menus.json';realWorldCustomerDataUsed=$false;externalLiveDataCalled=$false}
 harnessRepairs=@('Wrong role heading label corrected after initial timeout','Confirmation render awaited before claiming command execution','Actual contract names create/authorizedRecipientIds/daily/netAmount corrected; failed attempts preserved','Automatic CSS import served an empty compressed asset; independent preview now serves a copy of the generated product scoped CSS directly; final styled captures supersede the unstyled visual evidence')
 finalReadOnlyUiSourceBinding=@{status='Passed';basis='Latest central compiled Ui.Common DLL and generated scoped CSS copied into separate preview output; no extra product build and no fake fallback';binaryProof='artifacts/local/apk-completion-r26/final-preview-binaries.json';readOnlyUiProof='artifacts/local/apk-completion-r26/final-styled-readonly-ui/verification.json';readOnlyHttpProof='artifacts/local/apk-completion-r26/final-styled-readonly-ui/http-evidence.json';retainedUnstyledProof='artifacts/local/apk-completion-r26/final-readonly-ui/verification.json';generatedCssSource='Ssalddel.Ui.Common/obj/Debug/net10.0/scopedcss/projectbundle/Ssalddel.Ui.Common.bundle.scp.css';generatedCssIsNotOriginalSource=$true;viewportWidths=@(320,390);screenshots=18;errors=0;mutationRequests=0;supportCommerceTouchTargetsAtLeast48px=$true;horizontalOverflow=$false;visualSamplesViewed=@('support-admin-320.png','orderer-390.png')}
}
[IO.File]::WriteAllText((Join-Path $taskArtifact 'actual-workflow-evidence.json'),($taskEvidence|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false))
@{status=$taskEvidence.status;foodScreenshots=$taskFoodRows.Count;supportScreenshots=$taskSupportRows.Count;uniqueScreenshotFiles=$taskScreens.Count;actualApiChecks=$taskGuard.rows.Count;orderNo=$taskFood.orderNo;caseId=$taskSupport.caseId}|ConvertTo-Json
