using Ssalddel.Contracts.Common.Community;
using Ssalddel.Contracts.Common.Content;
using Ssalddel.Contracts.Common.Inbound;
using Ssalddel.Contracts.Common.Mart;
using Ssalddel.Contracts.Common.Orderer;
using Ssalddel.Contracts.Common.Sales;
using Ssalddel.Contracts.Shipper;
using Ssalddel.Contracts.Shipper.Request;

namespace Ssalddel.Contracts.Common.Versioning;

public enum PageCapabilityMatchKind
{
    Exact,
    Prefix
}

public enum PageCapabilityStage
{
    Live,
    Beta,
    Experience,
    Preparing
}

public enum PageInteractionBoundary
{
    ReadOnly,
    PlatformPersistence,
    Simulation
}

public static class SsalddelPageAppCodes
{
    public const string IntegratedWeb = "Ssalddel.WebApp";
    public const string Admin = "SsalddelAdmin";
    public const string Driver = "DriverApp";
    public const string Orderer = "OrdererApp";
    public const string Shipper = "SsalddelApp";
    public const string Warehouse = "WarehouseManagerApp";
    public const string HumanResources = "HumanResourcesManagerApp";
    public const string RestaurantDesk = "RestaurantDeskApp";
    public const string FoodDeliveryDriver = "FoodDeliveryDriverApp";
}

public sealed record SsalddelPageCapabilityRule(
    string PageKey,
    string AppCode,
    string RoutePattern,
    PageCapabilityMatchKind MatchKind,
    PageCapabilityStage Stage,
    PageInteractionBoundary Boundary,
    bool RequiresAuthentication,
    bool HasExternalEffects,
    string IntroducedVersion,
    IReadOnlyList<string> FeatureKeys,
    IReadOnlyList<string> WorkflowCodes,
    string Notice);

public sealed class PageCapabilityDto
{
    public string PageKey { get; init; } = string.Empty;

    public string AppCode { get; init; } = string.Empty;

    public string RoutePattern { get; init; } = string.Empty;

    public string MatchKindCode { get; init; } = string.Empty;

    public string StageCode { get; init; } = string.Empty;

    public string StageName { get; init; } = string.Empty;

    public string BoundaryCode { get; init; } = string.Empty;

    public string BoundaryName { get; init; } = string.Empty;

    public bool RequiresAuthentication { get; init; }

    public bool HasExternalEffects { get; init; }

    public string IntroducedVersion { get; init; } = string.Empty;

    public IReadOnlyList<string> FeatureKeys { get; init; } = [];

    public bool IsFeatureEnabled { get; init; }

    public IReadOnlyList<string> WorkflowCodes { get; init; } = [];

    public string Notice { get; init; } = string.Empty;
}

public static class PageCapabilityLabels
{
    public static string StageName(PageCapabilityStage stage)
        => stage switch
        {
            PageCapabilityStage.Live => "운영",
            PageCapabilityStage.Beta => "베타",
            PageCapabilityStage.Experience => "체험",
            PageCapabilityStage.Preparing => "준비 중",
            _ => "준비 중"
        };

    public static string BoundaryName(PageInteractionBoundary boundary)
        => boundary switch
        {
            PageInteractionBoundary.ReadOnly => "조회",
            PageInteractionBoundary.PlatformPersistence => "플랫폼 저장",
            PageInteractionBoundary.Simulation => "Simulation",
            _ => "상태 확인"
        };
}

/// <summary>
/// 통합 웹의 실제 라우트 계열과 여러 역할 앱의 대표 진입점을 같은 기준으로 설명합니다.
/// 기능 플래그는 노출 가능성을, 실행 경계는 외부 효과 허용 여부를 각각 따로 표현합니다.
/// </summary>
public static partial class SsalddelPageCapabilityCatalog
{
    private const string Community = "CommunityTrustWorkflow";
    private const string DomesticTransport = "DomesticTransportWorkflow";
    private const string Warehouse = "WarehouseFulfillmentWorkflow";
    private const string Customs = "CustomsAndTradeDataWorkflow";
    private const string GroupPurchase = "GroupPurchaseDemandWorkflow";
    private const string GroupPurchasePractice = "GroupPurchasePracticeWorkflow";
    private const string Sales = "SalesChannelFulfillmentWorkflow";
    private const string Hr = "HrParticipationWorkflow";
    private const string Food = "FoodDeliveryWorkflow";
    private const string Mart = "SsalddelMartWorkflow";

    private static readonly IReadOnlyList<SsalddelPageCapabilityRule> Items =
    [
        Exact("web-home", SsalddelPageAppCodes.IntegratedWeb, "/", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0",
            "여덟 역할을 선택하고 같은 통합 앱의 역할별 지도 업무로 이동하는 시작점입니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("web-app-launcher", SsalddelPageAppCodes.IntegratedWeb, "/apps", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0",
            "여덟 역할을 선택하는 읽기 전용 화면입니다. 기존 독립 역할 앱의 직접 경로는 유지합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Prefix("role-web-apps", SsalddelPageAppCodes.IntegratedWeb, "/roles", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0",
            "01~05 역할별 독립 WebApp으로 이동하는 읽기 전용 진입 경로입니다."),
        Exact("web-login", SsalddelPageAppCodes.IntegratedWeb, "/login", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0",
            "회원가입은 선택이며, 가입할 때만 개인정보 수집·이용에 동의합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("web-not-found", SsalddelPageAppCodes.IntegratedWeb, "/not-found", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "찾을 수 없는 주소를 안전하게 안내합니다."),

        Exact("community-home", SsalddelPageAppCodes.IntegratedWeb, "/community", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0",
            "로그인하지 않아도 공개 글을 읽고 익명 글과 댓글을 등록할 수 있습니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-role-home", SsalddelPageAppCodes.IntegratedWeb, "/community/home", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0",
            "01 역할 WebApp에서 생활 이야기와 국내 공공정보를 읽기 전용으로 탐색합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-localized-home-template", SsalddelPageAppCodes.IntegratedWeb, "/{LanguageSegment}/community", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0",
            "국가 문맥과 분리된 화면 언어 경로에서 같은 공개 커뮤니티 기능을 제공합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-korean-home", SsalddelPageAppCodes.IntegratedWeb, "/ko/community", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0",
            "한국어 시스템 UI에서 공개 커뮤니티와 익명 참여를 제공합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-english-home", SsalddelPageAppCodes.IntegratedWeb, "/en/community", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0",
            "영문 시스템 UI에서 공개 커뮤니티를 제공하며 사용자 글은 원문을 유지합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-categories", SsalddelPageAppCodes.IntegratedWeb, "/community/categories", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0",
            "공개 커뮤니티 게시판 분류와 각 게시판 진입점을 읽기 전용으로 조회합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-board-directory", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.BoardDirectory, PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0",
            "일상 게시판과 전체 로드맵 버전의 비식별 Command·Event 활동 게시판을 모아 읽기 전용 진입점으로 제공합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-board-management", SsalddelPageAppCodes.IntegratedWeb, "/community/boards/manage", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "사용자가 게시판 개설을 신청하고 권한이 있는 운영자가 검토합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Prefix("community-boards", SsalddelPageAppCodes.IntegratedWeb, "/community/boards", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "공개 게시판과 게시판별 글을 조회합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Prefix("community-write", SsalddelPageAppCodes.IntegratedWeb, "/community/write", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "회원 또는 익명 작성자로 커뮤니티 글을 저장합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Prefix("community-posts", SsalddelPageAppCodes.IntegratedWeb, "/community/posts", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "공개 글과 익명 댓글을 조회하고 저장합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-workspace", SsalddelPageAppCodes.IntegratedWeb, "/community/workspace", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "게시판에서 합의한 필요를 업무·원장·다이어그램 화면으로 연결하는 허브입니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-map-application-chooser", SsalddelPageAppCodes.IntegratedWeb, "/community/map-application-chooser", PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "지도에서 선택한 대상으로 개별 주문·대리 주문·운송 신청 화면을 고르는 읽기 전용 진입 화면입니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-ledger-draft", SsalddelPageAppCodes.IntegratedWeb, "/community/ledgers/new", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "당사자가 합의할 조건과 담당 흐름을 공동 원장 초안으로 정리합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("shipper-community-home", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Home, PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "Web과 같은 공용 Screen에서 공개 커뮤니티를 읽고 명시적으로 참여합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("shipper-community-board-management", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.BoardManagement, PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "Web과 같은 공용 Screen에서 게시판 개설 신청과 권한 있는 검토를 수행합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("shipper-community-boards", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Boards, PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "선택·검색·필터·보기 문맥을 보존하며 공개 게시판 글을 조회합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("shipper-community-write", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Compose, PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "회원 또는 익명 작성자로 커뮤니티 글을 저장하고 출발 목록으로 돌아갑니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Prefix("shipper-community-posts", SsalddelPageAppCodes.Shipper, "/community/posts", PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "공개 글과 익명 댓글을 조회·저장하고 출발 목록 문맥을 복원합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("shipper-community-workspace", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Workspace, PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "게시판에서 합의한 필요를 업무·원장·다이어그램 화면으로 연결하는 공용 허브입니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("shipper-community-ledger-draft", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.LedgerDraft, PageCapabilityStage.Live,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "당사자가 합의할 조건과 담당 흐름을 Web과 같은 공용 원장 초안 Screen에서 정리합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-group-purchase-public", SsalddelPageAppCodes.IntegratedWeb, "/community/group-purchase", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "공개 공동구매 목록만 조회하며 선택한 모집은 campaign ID 상세 route에서 엽니다.",
            false, [Community], ["CommunityTrust"]),
        Exact("community-group-purchase-practice", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.GroupPurchasePractice, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "가상 이웃과 저장 없는 집단화 과정을 연습하며 실제 주문·결제·계약·연락처 전달은 실행하지 않습니다.",
            false, [Community, GroupPurchasePractice], ["CommunityTrust", "GroupPurchaseDemand"]),
        Exact("community-group-purchase-create", SsalddelPageAppCodes.IntegratedWeb, "/community/group-purchase/new", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "상품·수량·수령 조건을 비구속 공동구매 제안과 수요 투표로 저장하며 결제나 계약을 확정하지 않습니다.",
            true, [Community, GroupPurchase], ["CommunityTrust"]),
        Exact("community-group-purchase-demand", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.GroupPurchaseDemand, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, false, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "공개 재료 근거를 유지해 공동 할인 후보를 미리 보고, 로그인한 사용자가 동의한 경우에만 철회 가능한 개별주문 의향을 저장합니다.",
            false, [Community, GroupPurchase], ["CommunityTrust"]),
        Exact("shipper-community-group-purchase-demand", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.GroupPurchaseDemand, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, false, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "호환 route에서 재료 근거와 수령 조건을 확인하고 로그인한 사용자가 동의한 경우에만 개별주문 의향을 저장하거나 철회합니다.",
            false, [Community, GroupPurchase], ["CommunityTrust"]),
        Exact("shipper-community-individual-order-start", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.IndividualOrderStart, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, false, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "커뮤니티에서 고른 재료를 개인 수령 조건과 함께 기록하고 별도 동의가 있을 때만 같이 주문 할인 후보에 연결합니다.",
            false, [Community, GroupPurchase], ["CommunityTrust", "GroupPurchaseDemand"]),
        Exact("shipper-community-individual-orders", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.IndividualOrders, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "로그인한 사용자가 자신의 개별주문 의향과 같이 주문 후보 연결 상태만 조회하고 철회합니다.",
            false, [Community, GroupPurchase], ["CommunityTrust"]),
        Prefix("community-group-purchase", SsalddelPageAppCodes.IntegratedWeb, "/community/group-purchase", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion, "campaign ID의 공개 상세를 읽고 참여·합의 Command는 화면과 서버에서 별도로 인증하며 실제 결제·계약·자동 배차는 실행하지 않습니다.", true,
            [Community, GroupPurchase], ["CommunityTrust", "GroupPurchaseDemand"]),
        Prefix("community-group-import", SsalddelPageAppCodes.IntegratedWeb, "/community/group-import", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion, "같이 수입의 공급·물류·비용 연결 구조를 Simulation으로 살펴봅니다.", true,
            [Customs], ["GroupPurchaseImport", "CustomsAndTradeData"]),
        Prefix("community-global-trade", SsalddelPageAppCodes.IntegratedWeb, "/community/global-trade", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, SsalddelProductRoadmapCatalog.TradeReadinessVersion, "해외 공급자와 국내 참여자의 공개 대화 흐름을 체험합니다.", false,
            [Customs], ["CustomsAndTradeData", "CommunityTrust"]),
        Prefix("community-actions", SsalddelPageAppCodes.IntegratedWeb, "/community/actions", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, "0.0", "관심과 참여를 명시적으로 나누며 실제 실행 전 단계까지만 검증합니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("community-bagua", SsalddelPageAppCodes.IntegratedWeb, "/community/bagua", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, "0.0", "대화에서 공동행동으로 이어지는 다이어그램 전환을 체험합니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("community-discover", SsalddelPageAppCodes.IntegratedWeb, "/community/discover", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "0.0", "공개 정보에 근거한 주변 후보를 조회합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Prefix("community-safety", SsalddelPageAppCodes.IntegratedWeb, "/community/safety", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "0.0", "신고와 안전 조치 흐름을 로그인 사용자 기준으로 검증합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-role-application", SsalddelPageAppCodes.IntegratedWeb, "/community/roles/apply", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "2.5",
            "자발적인 역할 관심을 최소 정보로 저장하고 본인이 철회하며, 역할 배정·채용·계약·보수는 실행하지 않습니다.",
            featureKeys: [Hr], workflowCodes: ["HrParticipation", "CommunityTrust"]),
        Prefix("community-personal", SsalddelPageAppCodes.IntegratedWeb, "/community/me", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "0.0", "내 글·참여·원장·알림과 개인 설정을 관리합니다.",
            featureKeys: [Community], workflowCodes: ["CommunityTrust"]),
        Exact("community-decoration-store", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.Decorations, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, false, "0.0", "Web과 모바일이 공유하는 공개 꾸미기 상품 목록이며 조회만으로 보유·적용 상태를 바꾸지 않습니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("community-decoration-products", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.DecorationProducts, PageCapabilityStage.Experience,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "stable 상품 key 한 건을 읽고 이미 보유한 꾸미기의 로컬 적용 선택만 저장하며 구매·결제를 실행하지 않습니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("community-decoration-checkout", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.DecorationCheckout, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "0.0", "명시적 확인 뒤 개발용 FakePG 보유권만 기록하며 실제 카드 승인·청구·정산을 실행하지 않습니다.", true,
            [Community], ["CommunityTrust"]),
        Prefix("community-decoration-legacy", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.Decorations, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "0.0", "기존 상품·checkout 주소를 책임별 canonical route로 교체 이동하며 FakePG 경계를 보수적으로 유지합니다.", true,
            [Community], ["CommunityTrust"]),
        Exact("shipper-app-community-decoration-store", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Decorations, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, false, "0.0", "Web과 같은 공용 Screen에서 공개 꾸미기 상품 목록만 탐색합니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("shipper-app-community-decoration-products", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.DecorationProducts, PageCapabilityStage.Experience,
            PageInteractionBoundary.PlatformPersistence, false, "0.0", "Web과 같은 stable 상품 key 상세에서 이미 보유한 꾸미기의 로컬 적용 선택만 저장하며 구매·결제를 실행하지 않습니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("shipper-app-community-decoration-checkout", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.DecorationCheckout, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "0.0", "명시적 확인 뒤 개발용 FakePG 또는 계정 보유권 adapter만 호출하며 실제 금전 이동을 실행하지 않습니다.", true,
            [Community], ["CommunityTrust"]),
        Prefix("shipper-app-community-decoration-legacy", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Decorations, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "0.0", "기존 모바일 상품·checkout 주소를 책임별 canonical route로 교체 이동합니다.", true,
            [Community], ["CommunityTrust"]),

        .. CreateNeighborhoodExchangeItems(),
        .. CreateCommerceProtectionItems(),
        .. CreateProtectionSupportItems(),
        .. CreateRoleWorkspaceItems(),
        .. CreatePublicInformationItems(),
        Exact("us-korean-food-group-buy", SsalddelPageAppCodes.IntegratedWeb, "/us/korean-food-group-buy", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion, "한국 음식과 식재료를 공개 탐색하고 로그인 사용자의 비구속 수요만 미국 ZIP 단위 자동집단에 기록합니다. 결제·주문·통관 신고는 실행하지 않습니다.", false,
            [GroupPurchase], ["GroupPurchaseDemand"]),

        Exact("global-home", SsalddelPageAppCodes.IntegratedWeb, "/global", PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, false, "2.0", "해외 상품과 공급 조건을 공개 탐색합니다.",
            featureKeys: [Customs], workflowCodes: ["CustomsAndTradeData"]),
        Prefix("global-products", SsalddelPageAppCodes.IntegratedWeb, "/global/products", PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, false, "2.0", "샘플 상품의 상세 정보와 수입 검토 항목을 조회합니다.",
            featureKeys: [Customs], workflowCodes: ["CustomsAndTradeData"]),
        Prefix("global-suppliers", SsalddelPageAppCodes.IntegratedWeb, "/global/suppliers", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, "2.0", "공급자 제출 내용은 체험 세션에서만 다룹니다.", false,
            [Customs], ["CustomsAndTradeData"]),
        Prefix("global-import-requests", SsalddelPageAppCodes.IntegratedWeb, "/global/import-requests", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5", "수입 요청을 Simulation 원장으로 검토합니다.", true,
            [GroupPurchase, Customs], ["GroupPurchaseImport", "CustomsAndTradeData"]),
        Prefix("global-orders", SsalddelPageAppCodes.IntegratedWeb, "/global/orders", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5", "수입 주문 원장의 연결 구조를 체험합니다.", true,
            [GroupPurchase, Customs], ["GroupPurchaseImport", "CustomsAndTradeData"]),

        Prefix("shipper-public-cargo", SsalddelPageAppCodes.IntegratedWeb, "/shipper/public-cargo", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.TransportVersion,
            "화주가 공개에 동의한 비식별 화물 정보만 조회합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Exact("shipper-payment-status", SsalddelPageAppCodes.IntegratedWeb, "/shipper/request/payment-status", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "stable 운송 의뢰 ID를 받아 읽기 전용 결제·정산 상태 화면으로 연결하며 결제·입금·정산 Command를 실행하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "운송 의뢰 초안을 작성하고 명시적으로 원장을 저장하며 자동 배차·계약·결제를 확정하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-cargo", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Cargo, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "한 운송 의뢰 초안의 화물 조건만 작성하고 자동 저장합니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-transport", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Transport, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "한 운송 의뢰 초안의 상·하차와 운송 조건만 작성하고 자동 저장합니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-procedure", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Procedure, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "한 운송 의뢰 초안의 수행 절차와 결제 조건만 작성하며 실제 결제를 실행하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-review", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Review, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "작성된 조건을 최종 확인하고 명시적으로 운송 의뢰 원장만 등록합니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-review-legacy", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.LegacySummary, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기존 최종 확인 주소이며 같은 운송 의뢰 원장 등록 경계를 사용합니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-bulk", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Bulk, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "대량 의뢰를 행별로 검증하고 미리 보지만 현재 운영 원장에 자동 등록하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-request-detail-lookup", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestDetailPageRoutes.LegacyLookup, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "stable 운송 의뢰 ID를 입력해 책임별 상세 화면으로 이동합니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("shipper-request-detail", SsalddelPageAppCodes.IntegratedWeb, ShipperRequestPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "한 운송 의뢰의 요약·이력·결제 상태·증빙을 책임별 화면에서 다시 조회하며 상태 변경 Command를 실행하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("shipper-inbound-dashboard", SsalddelPageAppCodes.IntegratedWeb, "/shipper/inbound/dashboard", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "사용자 소유 창고·입고·재고 요약을 서버 원장에서 조회하며 상태를 변경하지 않습니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("shipper-inbound-list", SsalddelPageAppCodes.IntegratedWeb, InboundRequestPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "사용자 소유 입고 요청 목록을 서버에서 조회하고 stable ID 상세로 이동합니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("shipper-inbound-create", SsalddelPageAppCodes.IntegratedWeb, InboundRequestPageRoutes.Create, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "입고 요청 한 건을 명시적으로 서버 원장에 저장하며 입고 완료·검수·재고 생성은 실행하지 않습니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("shipper-warehouse-create", SsalddelPageAppCodes.IntegratedWeb, InboundRequestPageRoutes.WarehouseRegistration, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "사용자 소유 창고 기준정보 한 건을 서버 원장에 등록하며 보관 계약을 자동 확정하지 않습니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Prefix("shipper-inbound", SsalddelPageAppCodes.IntegratedWeb, InboundRequestPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "stable ID 상세는 읽기 전용이며 완료 전용 route에서만 입고상품·재고 전환을 명시적으로 저장합니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("shipper-warehouse-workspace", SsalddelPageAppCodes.IntegratedWeb, "/shipper/warehouse/workspace", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "입고·재고·출고 목적별 화면으로 이동하는 읽기 전용 화주 창고 허브입니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("shipper-warehouse-inventory", SsalddelPageAppCodes.IntegratedWeb, "/shipper/warehouse/inventory", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "사용자 소유 재고를 조회하고 판매상품 등록·재위탁은 독립 화면으로 넘깁니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("shipper-warehouse-scan", SsalddelPageAppCodes.IntegratedWeb, "/shipper/warehouse/scan", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "브라우저 바코드 입력과 작업 요건을 로컬 Simulation으로 검증하며 서버 재고를 변경하지 않습니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Prefix("shipper-warehouse", SsalddelPageAppCodes.IntegratedWeb, "/shipper/warehouse", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "화주 관점의 창고·재고 흐름을 Simulation으로 검증합니다.", true,
            [Warehouse], ["WarehouseFulfillment"]),
        Prefix("shipper-exploration", SsalddelPageAppCodes.IntegratedWeb, "/shipper/exploration", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "운행 가능성 문의를 계약·배차 확정과 분리해 검증합니다.", true,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("shipper-reconsignment", SsalddelPageAppCodes.IntegratedWeb, "/shipper/reconsignment", PageCapabilityStage.Preparing,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "2.5 재고에서 2.0 운송 의뢰로 넘기는 재위탁 초안을 실제 배차 없이 준비합니다.", true,
            [Warehouse, DomesticTransport], ["WarehouseFulfillment", "DomesticTransport"]),
        Exact("shipper-sales-channels", SsalddelPageAppCodes.IntegratedWeb, "/shipper/sales/channels", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "2.5",
            "사용자 소유 판매채널 연결 준비 원장을 조회·저장하며 외부 인증·발행·주문 동기화는 실행하지 않습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-sales-orders", SsalddelPageAppCodes.IntegratedWeb, SalesOrderPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "재고 예약과 함께 영속된 사용자 소유 판매채널 주문 출고 후보만 조회하며 외부 주문 수집과 출고 실행은 하지 않습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-sales-order-routes", SsalddelPageAppCodes.IntegratedWeb, SalesOrderPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "Web과 모바일이 공유하는 stable 주문 ID 상세 경로이며 사용자 소유 영속 출고 후보만 읽습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-sales-products", SsalddelPageAppCodes.IntegratedWeb, "/shipper/sales/products", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "입고 재고에서 명시적으로 생성된 사용자 소유 판매상품 원장만 조회합니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-sales-product-create", SsalddelPageAppCodes.IntegratedWeb, "/shipper/sales/products/new", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "선택한 재고 ID 한 건으로 내부 판매상품을 저장하며 채널 출품·외부 발행은 실행하지 않습니다.", false,
            [Sales, Warehouse], ["SalesChannelFulfillment", "WarehouseFulfillment"]),
        Exact("shipper-sales-listings", SsalddelPageAppCodes.IntegratedWeb, "/shipper/sales/listings", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "사용자 소유 판매상품과 채널계정의 내부 출품 준비 원장만 조회합니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-sales-listing-create", SsalddelPageAppCodes.IntegratedWeb, "/shipper/sales/listings/new", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "판매상품과 채널계정을 직접 선택해 내부 출품 준비 원장만 저장하며 외부 채널 발행은 실행하지 않습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-orders", SsalddelPageAppCodes.Shipper, SalesOrderPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "모바일 앱에서 Web과 같은 사용자 소유 판매 주문 원장을 읽으며 외부 주문 수집과 출고 실행은 하지 않습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-app-sales-order-routes", SsalddelPageAppCodes.Shipper, SalesOrderPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "모바일 앱의 stable 주문 ID 상세 경로이며 사용자 소유 영속 출고 후보만 읽습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-fulfillment", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Root, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "로컬 주문·재고·피킹·포장 요약과 목표별 진입점만 읽으며 상태를 변경하지 않습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-fulfillment-samples", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Samples, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5",
            "비식별 샘플 주문을 로컬 메모리 원장에만 명시적으로 반영하고 같은 원장을 다시 읽습니다.", true,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-app-sales-fulfillment-orders", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Orders, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "로컬 Simulation 주문 목록과 stable 주문 key 상세를 읽으며 피킹·포장 Command를 실행하지 않습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-fulfillment-inventory", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Inventory, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "로컬 마켓 재고 snapshot과 입고 필요 검토 신호만 읽습니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-fulfillment-picking", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Picking, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "로컬 피킹 task 목록만 읽고 Command는 stable task ID 하위 화면으로 넘깁니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-app-sales-fulfillment-picking-task", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Picking, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5",
            "주소의 정확한 피킹 task ID에만 스캔·보류·취소를 적용하고 같은 원장을 다시 읽습니다.", true,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-fulfillment-packing", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Packing, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "로컬 포장 task 목록만 읽고 Command는 stable task ID 하위 화면으로 넘깁니다.", false,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-app-sales-fulfillment-packing-task", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Packing, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5",
            "주소의 정확한 포장 task ID에만 시작·완료를 적용하고 같은 원장을 다시 읽습니다.", true,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-app-sales-fulfillment-restock-policy", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.RestockPolicy, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5",
            "판매자별 로컬 알림 동의 정책만 변경하며 실제 메시지를 발송하지 않습니다.", true,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-app-sales-fulfillment-fallback", SsalddelPageAppCodes.Shipper, OrderFulfillmentSimulationPageRoutes.Root, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5",
            "로컬 주문 이행 하위 화면이며 외부 주문·재고·출고·운송·결제에는 영향을 주지 않습니다.", true,
            [Sales], ["SalesChannelFulfillment"]),
        Prefix("shipper-sales", SsalddelPageAppCodes.IntegratedWeb, "/shipper/sales", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.5", "외부 판매채널 발행 없이 판매·출고 화면을 체험합니다.", true,
            [Sales], ["SalesChannelFulfillment"]),
        Exact("shipper-customs-hs-reviews", SsalddelPageAppCodes.IntegratedWeb, "/shipper/customs/hs-reviews", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "활성 HS 코드 원장과 공개 동의된 근거를 조회하며 품목분류·세율·신고를 확정하지 않습니다.", false,
            [Customs], ["CustomsAndTradeData"]),
        Prefix("shipper-customs", SsalddelPageAppCodes.IntegratedWeb, "/shipper/customs", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.0", "HS 코드 후보와 검토 상태를 체험하며 전문 판단을 확정하지 않습니다.", true,
            [Customs], ["CustomsAndTradeData"]),
        Prefix("shipper-international", SsalddelPageAppCodes.IntegratedWeb, "/shipper/international", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "2.0", "FCL/LCL 비용 판단을 Simulation으로 비교합니다.", true,
            [Customs], ["CustomsAndTradeData"]),
        Prefix("shipper-settings", SsalddelPageAppCodes.IntegratedWeb, "/shipper/settings", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "사용자별 화주 화면·프로필 설정을 관리합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Exact("shipper-home", SsalddelPageAppCodes.IntegratedWeb, ShipperHomePageRoutes.Root, PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "커뮤니티에서 시작해 기능 플래그가 허용한 화주 업무만 찾고, 허브 자체는 상태 변경 Command를 실행하지 않습니다.", false,
            [Community], ["CommunityTrust"]),
        Exact("shipper-app-home", SsalddelPageAppCodes.Shipper, ShipperHomePageRoutes.Root, PageCapabilityStage.Live,
            PageInteractionBoundary.ReadOnly, false, "0.0", "Web과 같은 공용 화주 허브 Screen에서 로그인·기능 플래그·읽기 요약을 확인하며 상태를 변경하지 않습니다.", false,
            [Community], ["CommunityTrust"]),
        Prefix("shipper-fallback", SsalddelPageAppCodes.IntegratedWeb, ShipperHomePageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "별도 capability가 없는 화주·판매자 운송 도구는 통합 베타 Simulation 경계를 유지합니다.", true,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("dispatch-address", SsalddelPageAppCodes.IntegratedWeb, "/dispatch", PageCapabilityStage.Preparing,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "주소 입력은 검증할 수 있지만 자동 배차는 비활성입니다.", true,
            [DomesticTransport], ["DomesticTransport"]),

        Exact("driver-recommendation-list", SsalddelPageAppCodes.IntegratedWeb, "/driver/recommendations", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "현재 기사에게 제시된 추천 목록만 조회하며 수락·거절 Command를 실행하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-recommendation-detail", SsalddelPageAppCodes.IntegratedWeb, "/driver/recommendations", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "추천 한 건의 경로·비용·적합성과 서버 원장 상태만 읽습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-dispatch-decisions", SsalddelPageAppCodes.IntegratedWeb, "/driver/dispatch-decisions", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 본인의 명시적 수락·거절만 전송하며 자동 계약·자동 배차와 브라우저 자동 거절을 실행하지 않습니다.", true,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("driver-current-transport", SsalddelPageAppCodes.IntegratedWeb, "/driver/transports/current", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "현재 기사에게 배정된 운송의 단계와 다음 전용 처리 화면만 조회하며 상태 Command를 실행하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("driver-transport-history", SsalddelPageAppCodes.IntegratedWeb, "/driver/transports/history", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 본인의 과거 운송 이력을 읽기 전용으로 조회합니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-transports", SsalddelPageAppCodes.IntegratedWeb, "/driver/transports", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "서버가 권한과 선행 상태를 검증한 운송에만 상차·하차·증빙 상태 전이를 요청합니다.", true,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-settlements", SsalddelPageAppCodes.IntegratedWeb, "/driver/settlements", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 월 정산 후보를 읽기 전용으로 조회하며 실지급을 실행하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-work", SsalddelPageAppCodes.IntegratedWeb, "/driver/work", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 본인의 운행 설정·시작·위치 갱신을 2.0 Simulation 경계에서 검증합니다.", true,
            [DomesticTransport], ["DomesticTransport"]),
        Exact("driver-proof-stage-selector", SsalddelPageAppCodes.IntegratedWeb, "/driver/transport/proof", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "이전 증빙 링크를 stable 운송 ID 기반 상차·하차 전용 화면으로 연결하며 상태를 변경하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-account", SsalddelPageAppCodes.IntegratedWeb, "/driver/account", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "민감정보 마스킹과 기사 정산 계좌 설정 흐름을 검증합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Prefix("driver-profile", SsalddelPageAppCodes.IntegratedWeb, "/driver/me", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 개인 설정을 관리합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Exact("driver-notification-inbox", SsalddelPageAppCodes.IntegratedWeb, "/driver/notifications", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "실제 수신 payload를 전용 업무 화면으로 연결하며 영속 알림 목록이나 상태 변경을 가장하지 않습니다.", false,
            [DomesticTransport], ["DomesticTransport"]),
        Prefix("driver-notifications", SsalddelPageAppCodes.IntegratedWeb, "/driver/notifications", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 알림 수신 설정과 푸시 토큰을 본인 권한으로 관리합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Prefix("driver-settings", SsalddelPageAppCodes.IntegratedWeb, "/driver/settings", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 화면 설정을 관리합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Exact("driver-home", SsalddelPageAppCodes.IntegratedWeb, "/driver", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 업무 현황과 다음 전용 화면 진입점만 조회합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Exact("driver-home-alias", SsalddelPageAppCodes.IntegratedWeb, "/driver/home", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "기사 업무 현황과 다음 전용 화면 진입점만 조회합니다.",
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),
        Prefix("driver-fallback", SsalddelPageAppCodes.IntegratedWeb, "/driver", PageCapabilityStage.Preparing,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TransportVersion,
            "별도 capability가 없는 기사 도구는 2.0 준비 Simulation 경계를 유지합니다.", true,
            featureKeys: [DomesticTransport], workflowCodes: ["DomesticTransport"]),

        Exact("web-warehouse-mart-home", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/mart", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5", "마트 입고·재고·피킹의 책임별 서버 원장 화면 진입점만 제공하며 상태를 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-warehouse-mart-work-board", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/mart/work-board", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5", "고정 샘플 현황 없이 입고·재고·피킹 서버 원장으로 이동하는 읽기 전용 허브입니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-warehouse-mart-work-start", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/mart/work", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, "3.5", "로컬 작업자 진입 흐름만 검증하며 실제 입고·재고·포장·배달 인계 상태를 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-warehouse-mart-picking", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/mart/picking", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "로그인 계정이 접근할 수 있는 영속 마트 주문과 피킹·포장 작업만 조회합니다.",
            featureKeys: [Mart], workflowCodes: ["SsalddelMart"]),
        Prefix("web-warehouse-mart-picking-orders", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/mart/picking/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "주소의 정확한 주문 ID 한 건과 접근 가능한 피킹·포장 작업만 조회하며 상태는 변경하지 않습니다.",
            featureKeys: [Mart], workflowCodes: ["SsalddelMart"]),
        Exact("web-warehouse-inbound-products", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/inbound/products", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "정확한 상품 바코드로 입고예정을 조회하고, 명시적 도착·수령 기록으로 검수 대기 재고 한 건을 만든 뒤 같은 입고 ID를 다시 조회합니다. 현장 반입 요청은 후속 단계를 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-inbound-products-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/inbound/products", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 입고상품 수령 호환 경로입니다. 선택한 입고예정 한 건의 도착·수령만 명시적으로 저장하며 검수·적재는 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-inbound-inspection", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/inbound/inspection", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "접근 가능한 입고 완료 상품의 검수 결과를 서버 원장에 저장하고 같은 ID를 다시 조회합니다. 적재·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-inbound-inspection-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/inbound/inspection", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 입고 검수 호환 경로입니다. 운영 창고 원장에 검수 결과를 저장하며 적재·출고·운송·정산은 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Prefix("web-warehouse-inbound-inspection-routes", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/inbound/inspection", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "입고 검수 stable-ID 상세와 실행 경로입니다. 목록·상세는 읽기 전용이고 실행 경로만 검수 결과를 저장한 뒤 같은 ID를 다시 조회하며 적재·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Prefix("web-warehouse-inbound-inspection-alias-routes", SsalddelPageAppCodes.IntegratedWeb, "/work/inbound/inspection", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 입고 검수 stable-ID 호환 경로입니다. 실행 경로 외에는 상태를 변경하지 않으며 적재·출고·운송·정산을 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-inventory-overview", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/general/inventory", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "현재 계정의 창고 소유·배정 범위에서 최소 재고 목록과 명시한 입고상품 근거만 조회합니다. 사용자 ID와 계약·정산 내용은 노출하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-inventory-overview-alias", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/inventory", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 창고 재고 현황 호환 경로이며 창고 접근 범위의 최소 재고 정보만 읽고 계약·정산 내용은 노출하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-put-away-task", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/inbound/put-away", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "검수 완료 재고 한 건의 확인된 보관 위치만 저장하고 같은 입고상품 ID를 다시 조회합니다. 위치 이동·출고·운송·계약·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-put-away-task-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/inbound/put-away", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 적재 작업 호환 경로입니다. 운영 창고 원장에 검수 완료 재고의 위치 확정만 저장합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-packing-task", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/outbound/packing", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "적재 완료 재고의 전체 가용수량 포장 사실만 저장하고 같은 입고상품 ID를 다시 조회합니다. 재고 차감·출고·운송·계약·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-packing-task-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/outbound/packing", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 포장 작업 호환 경로입니다. 적재 완료 재고의 출고 준비 포장 사실만 Simulation으로 저장합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-outbound-handoff", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/general/transport-handoff", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "포장 완료 재고의 전체 가용수량을 출고예정 원장에 한 번만 기록합니다. 재고 예약·차감, 운송의뢰·배차·결제·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-outbound-handoff-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/outbound/handoff", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 출고 인계 준비 호환 경로입니다. 출고예정 원장 준비만 저장하고 실제 운송 효과는 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-outbound-plan-review", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/general/outbound-plan-review", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "준비된 출고예정 원장의 포장·수량·출발지 근거와 운송의뢰 입력 필요 항목을 읽기 전용으로 검토합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-outbound-plan-review-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/outbound/plans", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 출고예정 운송 전 검토 호환 경로입니다. 출고예정·재고·운송 상태를 변경하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-transport-request-draft", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/general/transport-request-draft", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "검토를 통과한 출고예정의 실제 하차지·희망 일정·차량 조건을 확인한 뒤 명시적으로 운송의뢰를 저장하고 같은 출고예정 ID의 기사 인계 상태를 다시 조회합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-transport-request-draft-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/outbound/transport-request-draft", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 출고 운송의뢰 호환 경로입니다. 명시적 저장에서만 출고 수량을 예약하고 운송의뢰를 생성하며 배차 수락·결제·정산은 별도 단계가 맡습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-picking-task", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/picking-batch", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "접근 가능한 피킹 작업의 대기·진행중·완료 상태만 서버에 저장하고 같은 작업 Key를 다시 조회합니다. 재고·포장·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-picking-task-alias", SsalddelPageAppCodes.IntegratedWeb, "/work/picking-batch", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 피킹 작업 호환 경로입니다. 서버 Simulation 피킹 상태만 저장하며 재고·포장·출고·운송·정산은 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Prefix("web-warehouse-picking-task-routes", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work/picking-batch", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "피킹 작업 stable-key 상세와 실행 경로입니다. 목록·상세는 읽기 전용이고 실행 경로만 시작·완료 상태를 바꾼 뒤 같은 Key를 다시 조회하며 재고·포장·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Prefix("web-warehouse-picking-task-alias-routes", SsalddelPageAppCodes.IntegratedWeb, "/work/picking-batch", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "통합 웹의 피킹 작업 stable-key 호환 경로입니다. 실행 경로 외에는 상태를 변경하지 않으며 재고·포장·출고·운송·정산을 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("web-warehouse-home", SsalddelPageAppCodes.IntegratedWeb, "/warehouse", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "창고 역할의 목적별 2.5 화면 진입점만 제공하며 작업 상태를 변경하지 않습니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("web-warehouse-work-board", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/work-board", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "고정 샘플 작업 없이 목적별 서버 원장 화면으로 이동하는 읽기 전용 허브입니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("web-warehouse-scan", SsalddelPageAppCodes.IntegratedWeb, "/warehouse/scan", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "브라우저 바코드 입력과 작업 요건을 로컬 Simulation으로 검증하며 서버 재고를 변경하지 않습니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Prefix("warehouse", SsalddelPageAppCodes.IntegratedWeb, "/warehouse", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "입고·검수·피킹·포장을 실제 보관 계약과 분리해 검증합니다.", true,
            [Warehouse, Mart], ["WarehouseFulfillment", "SsalddelMart"]),
        Prefix("warehouse-work-alias", SsalddelPageAppCodes.IntegratedWeb, "/work", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "창고 현장 호환 경로이며 Simulation 경계를 유지합니다.", true,
            [Warehouse, Mart], ["WarehouseFulfillment", "SsalddelMart"]),
        Exact("warehouse-work-board-alias", SsalddelPageAppCodes.IntegratedWeb, "/work-board", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "창고 작업 보드 호환 경로이며 목적별 서버 원장 화면으로만 이동합니다.", false,
            [Warehouse], ["WarehouseFulfillment"]),
        Exact("warehouse-app-expected-inbounds", SsalddelPageAppCodes.Warehouse, "/warehouse/inbounds/expected", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "창고 역할과 HR 세부 역할을 확인한 뒤 서버의 입고 예정 목록을 조회합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-work-board", SsalddelPageAppCodes.Warehouse, "/work-board", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "선택한 입고 요청을 같은 ID로 다시 조회하고 서버 상태에 따른 다음 업무를 확인합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-inbound-products", SsalddelPageAppCodes.Warehouse, "/work/inbound/products", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "정확한 상품 바코드로 입고예정을 조회하고, 명시적 도착·수령 기록으로 검수 대기 재고 한 건을 만든 뒤 같은 입고 ID를 다시 조회합니다. 현장 반입 요청은 후속 단계를 자동 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-inbound-inspection", SsalddelPageAppCodes.Warehouse, "/work/inbound/inspection", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "접근 가능한 입고 완료 상품의 검수 결과를 서버 원장에 저장하고 같은 ID를 다시 조회합니다. 적재·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Prefix("warehouse-app-inbound-inspection-routes", SsalddelPageAppCodes.Warehouse, "/work/inbound/inspection", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "입고 검수 stable-ID 상세와 실행 경로입니다. 목록·상세는 읽기 전용이고 실행 경로만 검수 결과를 저장한 뒤 같은 ID를 다시 조회하며 적재·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-inventory-overview", SsalddelPageAppCodes.Warehouse, "/warehouse/general/inventory", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "현재 계정의 창고 소유·배정 범위에서 최소 재고 목록과 명시한 입고상품 근거만 조회합니다. 사용자 ID와 계약·정산 내용은 노출하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-put-away-task", SsalddelPageAppCodes.Warehouse, "/work/inbound/put-away", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "검수 완료 재고 한 건의 확인된 보관 위치만 저장하고 같은 입고상품 ID를 다시 조회합니다. 위치 이동·출고·운송·계약·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-packing-task", SsalddelPageAppCodes.Warehouse, "/work/outbound/packing", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "적재 완료 재고의 전체 가용수량 포장 사실만 저장하고 같은 입고상품 ID를 다시 조회합니다. 재고 차감·출고·운송·계약·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-outbound-handoff", SsalddelPageAppCodes.Warehouse, "/warehouse/general/transport-handoff", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "포장 완료 재고의 전체 가용수량을 출고예정 원장에 한 번만 기록합니다. 재고 예약·차감, 운송의뢰·배차·결제·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-outbound-plan-review", SsalddelPageAppCodes.Warehouse, "/warehouse/general/outbound-plan-review", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "준비된 출고예정 원장의 포장·수량·출발지 근거와 운송의뢰 입력 필요 항목을 읽기 전용으로 검토합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-transport-request-draft", SsalddelPageAppCodes.Warehouse, "/warehouse/general/transport-request-draft", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "검토를 통과한 출고예정의 실제 하차지·희망 일정·차량 조건을 확인한 뒤 명시적으로 운송의뢰를 저장하고 같은 출고예정 ID의 기사 인계 상태를 다시 조회합니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-picking-task", SsalddelPageAppCodes.Warehouse, "/work/picking-batch", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "접근 가능한 피킹 작업의 대기·진행중·완료 상태만 서버에 저장하고 같은 작업 Key를 다시 조회합니다. 재고·포장·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Prefix("warehouse-app-picking-task-routes", SsalddelPageAppCodes.Warehouse, "/work/picking-batch", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion,
            "피킹 작업 stable-key 상세와 실행 경로입니다. 목록·상세는 읽기 전용이고 실행 경로만 시작·완료 상태를 바꾼 뒤 같은 Key를 다시 조회하며 재고·포장·출고·운송·정산은 실행하지 않습니다.",
            featureKeys: [Warehouse], workflowCodes: ["WarehouseFulfillment"]),
        Exact("warehouse-app-mart-picking", SsalddelPageAppCodes.Warehouse, "/mart/picking", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "접근 가능한 창고의 영속 마트 주문과 피킹·포장 작업을 조회하며 상태는 변경하지 않습니다.",
            featureKeys: [Mart], workflowCodes: ["SsalddelMart"]),
        Prefix("warehouse-app-mart-picking-orders", SsalddelPageAppCodes.Warehouse, "/mart/picking/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "주소의 정확한 주문 ID 한 건과 접근 가능한 피킹·포장 작업만 조회하며 상태는 변경하지 않습니다.",
            featureKeys: [Mart], workflowCodes: ["SsalddelMart"]),
        Exact("warehouse-app-mart-home", SsalddelPageAppCodes.Warehouse, "/mart", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "마트 입고·재고·피킹의 책임별 서버 원장 화면 진입점만 제공하며 상태를 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("warehouse-app-mart-work-board", SsalddelPageAppCodes.Warehouse, "/mart/work-board", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "고정 샘플 현황 없이 입고·재고·피킹 서버 원장으로 이동하는 읽기 전용 허브입니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("warehouse-app-mart-work-start", SsalddelPageAppCodes.Warehouse, "/mart/work", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "3.5", "로컬 작업자 진입 흐름만 검증하며 실제 입고·재고·포장·배달 인계 상태를 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-mart-home-alias", SsalddelPageAppCodes.IntegratedWeb, "/mart", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5", "통합 웹의 마트 업무 홈 호환 경로이며 책임별 서버 원장 화면 진입점만 제공합니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-mart-work-board-alias", SsalddelPageAppCodes.IntegratedWeb, "/mart/work-board", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5", "통합 웹의 마트 업무 흐름 호환 경로이며 고정 샘플 현황을 표시하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-mart-work-start-alias", SsalddelPageAppCodes.IntegratedWeb, "/mart/work", PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, "3.5", "통합 웹 호환 경로에서 로컬 작업자 진입 흐름만 검증하며 실제 업무 상태를 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-mart-picking-alias", SsalddelPageAppCodes.IntegratedWeb, "/mart/picking", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "통합 웹의 마트 피킹 호환 경로이며 영속 작업을 읽기 전용으로 조회합니다.",
            featureKeys: [Mart], workflowCodes: ["SsalddelMart"]),
        Prefix("web-mart-picking-orders-alias", SsalddelPageAppCodes.IntegratedWeb, "/mart/picking/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.5", "통합 웹 호환 경로에서 정확한 마트 주문 한 건과 접근 가능한 피킹·포장 작업만 조회합니다.",
            featureKeys: [Mart], workflowCodes: ["SsalddelMart"]),
        Prefix("mart-work", SsalddelPageAppCodes.IntegratedWeb, "/mart", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, "3.5", "도심 마트 작업을 Simulation 데이터로 검증합니다.", true,
            [Mart], ["SsalddelMart"]),
        Exact("warehouse-scan-alias", SsalddelPageAppCodes.IntegratedWeb, "/scan", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.FulfillmentVersion, "브라우저 스캔 입력을 Simulation으로 검증합니다.", true,
            [Warehouse], ["WarehouseFulfillment"]),

        Exact("web-orderer-mart-canonical", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5",
            "Web과 주문자 앱이 공유하는 마트 공개 상품 목록 route이며 조회만으로 주문·재고·배송 상태를 바꾸지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-orderer-mart-detail", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.DetailRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5",
            "stable product ID 한 건의 공개 상품·판매 가능 수량·구매 근거를 읽기 전용으로 조회합니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-orderer-mart-review", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.ReviewRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.5",
            "완료 원장 참여자가 한 공개 상품의 구매후기를 명시적으로 저장하고 같은 상품 ID를 다시 조회합니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-orderer-mart-order-request-canonical", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.OrderRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.5",
            "한 공개 상품의 비구속 주문 요청을 멱등 저장하고 같은 요청 ID를 다시 조회하며 재고·결제·출고 원장은 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-orderer-mart-order-request", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.LegacyWebOrderRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.5",
            "한 공개 상품의 비구속 주문 요청을 멱등 저장하고 같은 ID를 다시 조회하며 재고·결제·출고 원장은 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-orderer-mart-review-legacy", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.LegacyWebReviewRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.5",
            "기존 Web 경로에서 완료 원장 참여자의 공개 구매후기 저장 화면으로 연결합니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("web-orderer-mart-detail-legacy", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.LegacyWebDetailRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5",
            "기존 Web 경로에서 stable product ID 공개 상세를 읽기 전용으로 조회합니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-orderer-mart", SsalddelPageAppCodes.IntegratedWeb, MartProductPageRoutes.LegacyWebRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5",
            "내부 창고 원장과 분리된 공개 상품과 판매 가능 수량 투영을 익명으로 조회합니다.", false,
            [Mart], ["SsalddelMart"]),
        Exact("web-orderer-home", SsalddelPageAppCodes.IntegratedWeb, "/orderer", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "1.0 공동구매와 1.5 무역 준비 원장으로 이동하고 서버 준비 상태를 조회하는 주문자 점검 허브입니다.",
            false, [GroupPurchase, Customs], ["GroupPurchaseDemand", "CustomsAndTradeData"]),
        Exact("web-orderer-individual-import-ledger", SsalddelPageAppCodes.IntegratedWeb, "/orderer/ledgers/individual-import", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "개별주문 원본을 복제하지 않고 수입 준비 상태를 Simulation 원장으로 연결합니다.",
            false, [Customs], ["CustomsAndTradeData"]),
        Exact("web-orderer-individual-export-ledger", SsalddelPageAppCodes.IntegratedWeb, "/orderer/ledgers/individual-export", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "개별주문 원본을 복제하지 않고 수출 요건·서류 검토 상태를 Simulation 원장으로 연결합니다.",
            false, [Customs], ["CustomsAndTradeData"]),
        Exact("web-orderer-group-export-ledger", SsalddelPageAppCodes.IntegratedWeb, "/orderer/ledgers/group-export", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "개별수출 원장만 집계해 집하·합포장·포워더 인계 준비를 기록하고 신고 원본은 보존합니다.",
            false, [Customs], ["CustomsAndTradeData"]),
        Prefix("orderer-home", SsalddelPageAppCodes.IntegratedWeb, "/orderer", PageCapabilityStage.Beta,
            PageInteractionBoundary.Simulation, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion, "주문자 1.5 후속 경로를 Simulation 경계에서 점검합니다.", false,
            [GroupPurchase], ["GroupPurchaseDemand"]),
        Prefix("document-tools", SsalddelPageAppCodes.IntegratedWeb, "/tools", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "1.0", "업무 문서와 식별자 출력을 생성 전 미리 확인합니다."),
        Exact("diagram", SsalddelPageAppCodes.IntegratedWeb, CommunityPageRoutes.Diagram, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "0.0", "공동 원장과 업무 노드의 연결 구조를 체험합니다.", false,
            [Community], ["CommunityTrust"]),
        Exact("shipper-diagram", SsalddelPageAppCodes.Shipper, CommunityPageRoutes.Diagram, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, true, "0.0", "Web과 같은 공용 Screen에서 공동 원장과 업무 노드의 연결 구조를 탐색합니다.", false,
            [Community], ["CommunityTrust"]),

        Exact("admin-food-operations-list", SsalddelPageAppCodes.Admin, "/food-operations", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.0", "음식 주문 목록을 독립 조회하며 화물 기능 상태에 종속시키지 않습니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Prefix("admin-food-operations-detail", SsalddelPageAppCodes.Admin, "/food-operations/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.0", "선택한 음식 주문의 상태·다음 담당·배달 이력·정산을 조회하며 업무 명령을 실행하지 않습니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Prefix("admin-food-interruption-review", SsalddelPageAppCodes.Admin, "/food-operations/reviews", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.0", "최신 중단 시도와 근거를 조회한 운영자가 검토 결과를 명시 저장합니다. 배차·지급은 실행하지 않습니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Exact("admin-food-demand-surcharge", SsalddelPageAppCodes.Admin, "/food-operations/demand-surcharge", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.0", "최신 음식 배달 요금 정책의 허용 시간·금액을 확인한 뒤 한시 수요 할증을 명시 적용합니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Exact("admin-hr-dashboard", SsalddelPageAppCodes.Admin, "/dashboard", PageCapabilityStage.Preparing,
            PageInteractionBoundary.Simulation, true, "2.5", "역할·계약·4대보험 신고 준비를 실제 외부 신고와 분리해 검증합니다.", true,
            [Hr], ["HrParticipation"]),
        Exact("admin-group-import-trade-readiness", SsalddelPageAppCodes.Admin, "/trade-readiness", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "서버관리자가 승인된 1.0 수요 집단에 공급자·견적·원가·품목분류·국가별 검토와 책임 초안을 저장하며 계약·결제·신고·운송 실행은 열지 않습니다.", true,
            [GroupPurchase, Customs], ["GroupPurchaseDemand", "GroupPurchaseImport", "CustomsAndTradeData"]),
        Exact("human-resources-role-reviews", SsalddelPageAppCodes.HumanResources, "/", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "2.5",
            "서버관리자가 영속 HR 역할 지원·철회와 배정·해제 원장을 검색하고 정확한 검토 ID 상세를 조회합니다.",
            featureKeys: [Hr], workflowCodes: ["HrParticipation"]),
        Exact("orderer-group-purchase-home", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "공동구매 순서와 비구속 수요 집단화 경계를 읽기 전용으로 안내합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Exact("orderer-group-purchase-practice", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.Practice, PageCapabilityStage.Experience,
            PageInteractionBoundary.Simulation, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "로그인 없이 가상 이웃과 공동구매 집단화를 연습하고 실제 수요는 별도 화면에서 다시 확인합니다.",
            false, [Community, GroupPurchasePractice], ["CommunityTrust", "GroupPurchaseDemand"]),
        Exact("orderer-group-purchase-products", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.ProductsRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "공개 음식·재료 근거가 연결된 공동구매 후보 상품을 읽기 전용으로 탐색합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-group-purchase-product-detail", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.ProductsRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "한 상품의 재료·공공데이터·HS 근거를 읽되 구매·결제·계약을 실행하지 않습니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-order-mode-comparison", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.OrderModeComparisonRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "같은 상품과 수량의 개별주문·같이 주문 예상 총비용, 절감 가능성, 모집 진척과 추가 대기시간을 비교하며 기본 선택이나 자동 참여를 만들지 않습니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Exact("orderer-delivery-scope-finder", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.DeliveryScopesRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "주소에서 상세주소를 제거한 공개 배송권 후보를 확인하고 사용자가 직접 탐색 범위를 선택합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-delivery-scope-together-orders", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.DeliveryScopesRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "선택한 배송권에서 진행 중인 같이 주문의 공개 집계만 조회하며 참여자 식별자와 상세주소는 공개하지 않습니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-together-order-public-detail", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.TogetherOrdersRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "같이 주문의 상품·배송권·모집 진척·마감을 확인하고 비용 비교나 비구속 참여 의향으로 이동하되 자동 참여·결제·배송은 실행하지 않습니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-group-purchase-demand-create", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.DemandCreateRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "로그인한 주문자의 철회 가능한 주문 의향을 멱등 저장하고 공동 참여에 동의한 경우에만 1.0 집단화 후보로 인계하며 결제나 계약을 만들지 않습니다.", true,
            [GroupPurchase], ["GroupPurchaseDemand"]),
        Exact("orderer-group-purchase-wish-create", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.WishCreate, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "로그인한 주문자가 여러 재료의 주문 의향을 각각 독립된 개별 원장으로 저장하며 구매·결제·계약을 확정하지 않습니다.", true,
            [GroupPurchase], ["GroupPurchaseDemand"]),
        Exact("orderer-group-purchase-wishes", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.WishesRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "로그인한 주문자가 자신이 남긴 개별주문 원장과 1.0 같이 주문 인계 여부만 조회합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-group-purchase-wish-workspace", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.WishesRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "주문자 본인의 개별 원장을 조회하고 명시적으로 수정하거나 철회한 뒤 서버 상태를 다시 조회하며 결제·계약은 만들지 않습니다.", true,
            [GroupPurchase], ["GroupPurchaseDemand"]),
        Exact("orderer-group-purchase-groups", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.GroupsRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "로그인한 주문자의 개별 원함을 근거로 참여 중인 자동 집단 목록만 조회합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-group-purchase-group-detail", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.GroupsRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.GroupPurchaseVersion,
            "주문자 본인이 참여한 자동 집단의 공개 집계와 다음 준비 단계만 조회하며 다른 참여자의 개별 주문정보는 공개하지 않습니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Prefix("orderer-group-import-readiness", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.ImportsRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "참여 주문자가 같이 수입 원장별 공급자·원가·품목분류·포워더 인계·동의 준비 근거를 화면별로 조회하며 계약·결제·신고·운송은 실행하지 않습니다.", false,
            [GroupPurchase, Customs], ["GroupPurchaseDemand", "GroupPurchaseImport", "CustomsAndTradeData"]),
        Prefix("orderer-group-purchase-import-review", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.ImportReviewRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.TradeReadinessVersion,
            "승인된 수요 집단의 공급자·견적·원가·HSK/HTS·한국/미국 검토 근거를 확인하며 계약·결제·신고·운송은 실행하지 않습니다.", false,
            [GroupPurchase, Customs], ["GroupPurchaseDemand", "GroupPurchaseImport", "CustomsAndTradeData"]),
        Exact("orderer-group-purchase-shipments", SsalddelPageAppCodes.Orderer, GroupPurchasePageRoutes.Shipments, PageCapabilityStage.Experience,
            PageInteractionBoundary.ReadOnly, false, SsalddelProductRoadmapCatalog.TransportVersion,
            "문서관리번호가 별도로 발급된 기존 건의 공개 선적 상태만 읽는 2.0 준비 자산이며 1.5 흐름에서 선적·통관·운송 상태를 만들거나 변경하지 않습니다.", false,
            [DomesticTransport], ["GroupPurchaseImport", "DomesticTransport"]),
        Exact("orderer-food-home", SsalddelPageAppCodes.Orderer, "/food", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.0",
            "일반 음식점 주문 3.0과 마트 주문 3.5의 서로 다른 업무 경계로 이동하는 읽기 전용 진입점입니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Exact("orderer-food-restaurants", SsalddelPageAppCodes.Orderer, "/food/restaurants", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.0",
            "사용자가 선택한 공개 행정권역 기준점과 반경으로 영속된 공개 음식점·메뉴를 조회합니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Exact("orderer-orders", SsalddelPageAppCodes.Orderer, "/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "로그인한 주문자가 자신이 소유한 개별주문 원장 목록과 각 원장의 현재 업무 단계를 조회합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Exact("orderer-food-orders", SsalddelPageAppCodes.Orderer, "/orders/food", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, "3.0",
            "로그인한 주문자가 소유한 영속 음식 주문 목록과 정확한 주문번호 상세만 조회합니다.", false,
            [Food], ["FoodDelivery"]),
        Prefix("orderer-order-detail", SsalddelPageAppCodes.Orderer, "/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, true, SsalddelProductRoadmapCatalog.IndividualOrderVersion,
            "로그인한 주문자가 자신이 소유한 개별주문 원장 한 건과 연결된 이행 원장 식별자만 조회합니다.",
            featureKeys: [GroupPurchase], workflowCodes: ["GroupPurchaseDemand"]),
        Exact("orderer-mart", SsalddelPageAppCodes.Orderer, MartProductPageRoutes.Root, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5",
            "내부 창고 원장과 분리해 영속된 공개 상품·판매 가능 수량 투영을 조회하며 장바구니·주문·피킹·배송을 실행하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("orderer-mart-detail", SsalddelPageAppCodes.Orderer, MartProductPageRoutes.DetailRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.5",
            "stable product ID 한 건의 공개 상품·판매 가능 수량·구매 근거를 읽기 전용으로 조회합니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("orderer-mart-review", SsalddelPageAppCodes.Orderer, MartProductPageRoutes.ReviewRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.5",
            "완료 원장 참여자가 한 공개 상품의 구매후기를 명시적으로 저장하고 같은 상품 ID를 다시 조회합니다.", false,
            [Mart], ["SsalddelMart"]),
        Prefix("orderer-mart-order-request", SsalddelPageAppCodes.Orderer, MartProductPageRoutes.OrderRoot, PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.5",
            "한 공개 상품의 비구속 주문 요청을 멱등 저장하고 같은 ID를 다시 조회하며 재고·결제·출고 원장은 변경하지 않습니다.", false,
            [Mart], ["SsalddelMart"]),

        Exact("restaurant-desk-home", SsalddelPageAppCodes.RestaurantDesk, "/", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.0",
            "음식점 운영자가 주문 수신함과 주변 운영 도구로 이동하는 진입점이며 주문 상태를 직접 변경하지 않습니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Exact("restaurant-order-inbox", SsalddelPageAppCodes.RestaurantDesk, "/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.0",
            "설정된 음식점 ID의 실시간 주문 알림을 현재 실행 세션에서 조회하고 정확한 주문번호 상세로 이동합니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Prefix("restaurant-order-detail", SsalddelPageAppCodes.RestaurantDesk, "/orders", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, false, "3.0",
            "현재 실행 세션에서 수신한 정확한 주문번호 한 건을 명시적으로 수락하고 성공 응답으로만 전표를 출력합니다. 운영 인증 연결 전에는 Simulation에서만 사용합니다.", true,
            [Food], ["FoodDelivery"]),

        Exact("food-driver-home", SsalddelPageAppCodes.FoodDeliveryDriver, "/", PageCapabilityStage.Beta,
            PageInteractionBoundary.ReadOnly, false, "3.0",
            "음식 배달 기사가 배차·묶음·경로·정산 전용 업무로 이동하는 진입점입니다.",
            featureKeys: [Food], workflowCodes: ["FoodDelivery"]),
        Prefix("food-driver-workspace-launch", SsalddelPageAppCodes.FoodDeliveryDriver, "/food-delivery/open", PageCapabilityStage.Beta,
            PageInteractionBoundary.PlatformPersistence, true, "3.0",
            "로그인한 음식 배달 기사를 네이티브 지도 업무로 연결하며 수락·픽업·전달 완료는 각 Command에서 다시 권한과 상태를 검증합니다.", true,
            [Food], ["FoodDelivery"])
    ];

    public static IReadOnlyList<SsalddelPageCapabilityRule> GetAll() => Items;

    public static bool TryResolve(string appCode, string? route, out SsalddelPageCapabilityRule rule)
    {
        var normalizedRoute = NormalizeRoute(route);
        var match = Items
            .Where(item => string.Equals(item.AppCode, appCode, StringComparison.Ordinal))
            .Where(item => Matches(item, normalizedRoute))
            .OrderBy(item => item.MatchKind == PageCapabilityMatchKind.Exact ? 0 : 1)
            .ThenByDescending(item => item.RoutePattern.Length)
            .FirstOrDefault();

        if (match is null)
        {
            rule = default!;
            return false;
        }

        rule = match;
        return true;
    }

    private static bool Matches(SsalddelPageCapabilityRule rule, string route)
        => rule.MatchKind == PageCapabilityMatchKind.Exact
            ? string.Equals(rule.RoutePattern, route, StringComparison.OrdinalIgnoreCase)
            : string.Equals(rule.RoutePattern, route, StringComparison.OrdinalIgnoreCase)
              || route.StartsWith($"{rule.RoutePattern}/", StringComparison.OrdinalIgnoreCase);

    private static string NormalizeRoute(string? route)
    {
        var value = route?.Trim() ?? string.Empty;
        if (Uri.TryCreate(value, UriKind.Absolute, out var absoluteUri))
        {
            value = absoluteUri.AbsolutePath;
        }

        value = value.Split('?', '#')[0].Trim();
        if (string.IsNullOrEmpty(value))
        {
            return "/";
        }

        value = $"/{value.Trim('/')}";
        return value.Length == 1 ? value : value.TrimEnd('/');
    }

    private static SsalddelPageCapabilityRule Exact(
        string pageKey,
        string appCode,
        string route,
        PageCapabilityStage stage,
        PageInteractionBoundary boundary,
        bool requiresAuthentication,
        string introducedVersion,
        string notice,
        bool hasExternalEffects = false,
        string[]? featureKeys = null,
        string[]? workflowCodes = null)
        => Rule(pageKey, appCode, route, PageCapabilityMatchKind.Exact, stage, boundary,
            requiresAuthentication, introducedVersion, notice, hasExternalEffects, featureKeys, workflowCodes);

    private static SsalddelPageCapabilityRule Prefix(
        string pageKey,
        string appCode,
        string route,
        PageCapabilityStage stage,
        PageInteractionBoundary boundary,
        bool requiresAuthentication,
        string introducedVersion,
        string notice,
        bool hasExternalEffects = false,
        string[]? featureKeys = null,
        string[]? workflowCodes = null)
        => Rule(pageKey, appCode, route, PageCapabilityMatchKind.Prefix, stage, boundary,
            requiresAuthentication, introducedVersion, notice, hasExternalEffects, featureKeys, workflowCodes);

    private static SsalddelPageCapabilityRule Rule(
        string pageKey,
        string appCode,
        string route,
        PageCapabilityMatchKind matchKind,
        PageCapabilityStage stage,
        PageInteractionBoundary boundary,
        bool requiresAuthentication,
        string introducedVersion,
        string notice,
        bool hasExternalEffects,
        string[]? featureKeys,
        string[]? workflowCodes)
        => new(
            pageKey,
            appCode,
            NormalizeRoute(route),
            matchKind,
            stage,
            boundary,
            requiresAuthentication,
            hasExternalEffects,
            ResolveRoadmapVersion(pageKey, introducedVersion, featureKeys),
            featureKeys ?? [],
            workflowCodes ?? [],
            notice);

    private static string ResolveRoadmapVersion(
        string pageKey,
        string fallbackVersion,
        IReadOnlyCollection<string>? featureKeys)
    {
        if (string.Equals(pageKey, "us-korean-food-group-buy", StringComparison.Ordinal))
        {
            return SsalddelProductRoadmapCatalog.GroupPurchaseVersion;
        }

        // 0.5 개별주문 화면은 아직 GroupPurchaseDemandWorkflow를 호환 사용하지만,
        // 제품 도입 버전까지 1.0 같이 주문으로 끌어올리지는 않는다.
        if (string.Equals(
                fallbackVersion,
                SsalddelProductRoadmapCatalog.IndividualOrderVersion,
                StringComparison.Ordinal))
        {
            return SsalddelProductRoadmapCatalog.IndividualOrderVersion;
        }

        if (featureKeys?.Contains(Sales, StringComparer.Ordinal) == true
            || featureKeys?.Contains(Warehouse, StringComparer.Ordinal) == true
            || featureKeys?.Contains(Hr, StringComparer.Ordinal) == true)
        {
            return SsalddelProductRoadmapCatalog.FulfillmentVersion;
        }

        if (featureKeys?.Contains(DomesticTransport, StringComparer.Ordinal) == true)
        {
            return SsalddelProductRoadmapCatalog.TransportVersion;
        }

        if (featureKeys?.Contains(Customs, StringComparer.Ordinal) == true)
        {
            return SsalddelProductRoadmapCatalog.TradeReadinessVersion;
        }

        if (featureKeys?.Contains(GroupPurchase, StringComparer.Ordinal) == true
            || featureKeys?.Contains(GroupPurchasePractice, StringComparer.Ordinal) == true)
        {
            return SsalddelProductRoadmapCatalog.GroupPurchaseVersion;
        }

        return fallbackVersion;
    }
}
