<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ssalddel.CodeMetadata\Ssalddel.CodeMetadata.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Interior.Contracts\Ssalddel.Interior.Contracts.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Interior.Domain\Ssalddel.Interior.Domain.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Simulation.Application\Ssalddel.Simulation.Application.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Simulation.Contracts\Ssalddel.Simulation.Contracts.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Simulation.Domain\Ssalddel.Simulation.Domain.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Simulation.Infrastructure\Ssalddel.Simulation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Simulation.Persistence\Ssalddel.Simulation.Persistence.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Simulation.Hosting\Ssalddel.Simulation.Hosting.csproj" />
    <ProjectReference Include="..\..\Ssalddel.Unity\Ssalddel.Unity.csproj" />
  </ItemGroup>

</Project>
