using FluentResults;

namespace Ssalddel.Application.Shipper.Request;

public sealed record 의뢰생성Command(
    string? 화주Id,
    string? 운송방식,
    string? 차량종류,
    string? 결제수단,
    int? 결제예정금액,
    Ssalddel.Contracts.Shipper.Request.화주운송정산조건DTO? 정산조건,
    string 화물종류,
    string? 화물설명,
    int? 화물수량,
    int? 화물길이Mm,
    int? 화물폭Mm,
    int? 화물높이Mm,
    decimal? 화물중량Kg,
    decimal? 화물부피Cbm,
    int? 팔레트개수,
    bool 화물파손주의여부,
    string? 화물온도조건,
    string 픽업도로명주소,
    string? 픽업상세주소,
    decimal? 픽업위도,
    decimal? 픽업경도,
    string 픽업연락처이름,
    string 픽업연락처전화번호,
    DateTime 픽업시간창시작일시,
    DateTime 픽업시간창종료일시,
    string 하차도로명주소,
    string? 하차상세주소,
    decimal? 하차위도,
    decimal? 하차경도,
    string 하차연락처이름,
    string 하차연락처전화번호,
    DateTime? 하차시간창시작일시,
    DateTime? 하차시간창종료일시,
    string? 서비스레벨,
    string? 요청사항,
    decimal? 대기료,
    decimal? 수작업비,
    decimal? 할증,
    decimal? 예상거리Km,
    decimal? 기본운임,
    decimal? Km당단가,
    decimal? 거리운임,
    decimal? 최소운임,
    decimal? 최종운임,
    decimal? 기사지급예정운임,
    string? 클라이언트요청Id,
    string? 결제상태,
    string? 거리계산방식 = null,
    string? 단가출처 = null) : IRequest<Result<Ssalddel.Contracts.Shipper.Request.화주운송의뢰응답>>;
